### ISSUE TITLE
Game Editor: Variables

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#11]
We should be able to define variables (global) that carry out through out the scope of  the game.

Variables should have values for each player, each phone, for the time being at least.

However, I can foresee in the future that we could have team-scoped variables though for players to gather points collectively for instance.

We could Use the start state as a place for variable definition —use start state to configure global features such as this.

**Comment by mmicciolo** [comment]
Variables are 95% working. After basic global variables are working I am going to close this item and open new ones for enhancements on variables:
1. Button to add output varibles to outputstate (display text, photo url, video url, etc)
2. Single/Sequence/Key input to variable
