### ISSUE TITLE
Game Editor i18n Language Changes

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#119]

**Comment by mmicciolo** [comment]
This issue updates the language files with better wording. Below is an example of how to test this. Please feel free to to try and test it in ways other than the example below.

In the wlcp-platform-messages google sheet I highlighted all of the ones that made it over to the i18 English files with green.

TESTING INSTRUCTIONS :

1. Match the column "Object" from the google sheet to the key in the i18n file in wlcp-ui/webapp/i18n/i18n.properties
2. Compare the column "New Value" against the value in the i18n file in wlcp-ui/webapp/i18n/i18n.properties and make sure they match
3. You can also check to make sure the i18n file does not contain the "Original Value"

**Comment by mmicciolo** [comment]
Hello @franciscastro  @sai-educ @geseiche @IvonArroyo

This issue is ready for testing on https://dev.wearablelearning.org

In the comment above I have posted testing instructions.

Please post a comment here with the results of your testing.

Thanks!!

**Comment by geseiche** [comment]
Hi @mmicciolo, What branch should we be looking for these changes on?

**Comment by mmicciolo** [comment]
@geseiche 

Dev branch

**Comment by franciscastro** [comment]
@geseiche you'll need to pull the dev branch
