### ISSUE TITLE
Reset active transition when unselected and dialog closed / default to first available on open

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#122]

**Comment by mmicciolo** [comment]
This issue fixes a bug where if you selected a transition type and then closed the dialog it would remember that selection. Below is an example of how to test this. Please feel free to to try and test it in ways other than the example below.
**TESTING INSTRUCTIONS:**

1. Add a state (connection coming from start) with a display text for the Game Wide scope
2. Add another state below the newly created state
3. Add a connection between the two states
4. Add a transition to the connection
5. Double click the transition. Click on a transition type other than single button press
6. Cancel out of the dialog
7. Double click on the dialog again. Should revert back to single button press.

**Comment by mmicciolo** [comment]
Hello @franciscastro  @sai-educ  @geseiche  @IvonArroyo 

This issue is ready for testing on https://dev.wearablelearning.org

In the comment above I have posted testing instructions.

Please post a comment here with the results of your testing.

Thanks!!

**Comment by sai-educ** [comment]
Followed your instructions. This works as intended. The transition reverts back to the single button press.

**Comment by geseiche** [comment]
Tested. Works as intended. No issues

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
