### ISSUE TITLE
Logging flag in MetricsHelper.js not working

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#124]
The `loggingEnabled` flag in `MetricsHelper.js` does not enable `Logger` calls when logging.

What I've tried:
I enabled the `loggingEnabled` flag in `Logger.js`, which enabled `Logger` calls when logging, but it also enabled all the other `Logger` calls in the rest of the app. This drowns out all the `Logger` calls I'm making just for the purpose of debugging my logging work.

**Comment by mmicciolo** [comment]
Closed. This bug was fixed in the new Logger.js logger.
