### ISSUE TITLE
Saving a game with an existing name overwrites the game

### ISSUE THREAD

**Issue by sai-educ** [wearable-learning-cloud-platform/wlcp-issues#130]
Saving a game overwrites an existing game if there already is a file with that destination name. 

Steps to reproduce:
- Go to Game Editor
- Create a game and save it as _abc_
- Create another game and save it as _abc_ again

The original file gets overwritten. Need to add a name checker that checks for existing names before saving.

**Comment by geseiche** [comment]
This works on public games, private games, games owned by user, and games not owned by user

**Comment by mmicciolo** [comment]
This issue fixes a bug where you could create a new game with the same game name as one that already exists and overwrite it. Now you will receive a duplicate game name error. Below is an example of how to test this. Please feel free to to try and test it in ways other than the example below.
TESTING INSTRUCTIONS:

1. Try to create a game with the same name as one that already exists
2. You should receive a "game name" already exists error.
3. Test the same for copy + rename

**Comment by mmicciolo** [comment]
Hello @franciscastro @sai-educ @geseiche @IvonArroyo

This issue is ready for testing on https://dev.wearablelearning.org

In the comment above I have posted testing instructions.

Please post a comment here with the results of your testing.

Thanks!!

**Comment by geseiche** [comment]
There is an error while copying a game where if you give the copy the same name as someone else's existing game, it opens the existing game but changes the owner to the current user. Steps to recreate:

1. Load any game
2. Click copy and give it the title of an existing game that you do not own (e.g. others could use "testgrace")

After doing that the following occurs
1. "testgrace" is loaded on the screen
2. If you click Load, you will now notice "testgrace" appears under "Your Games"

**Comment by mmicciolo** [comment]
Hello @franciscastro @geseiche @sai-educ 

This issue is ready for retesting!

You should now receive a "Game Already Exists" error for new, copy and rename if that game already exists.

Improving the look of the error UI will be taken care of in another issue.

**Comment by mmicciolo** [comment]
Retesting Complete.
