### ISSUE TITLE
Button Sequence + Keyboard "already exists" validation not working

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#132]

**Comment by mmicciolo** [comment]
This issue fixes a bug where you could enter duplicate button sequences or text entry for a given scope. Below is an example of how to test this. Please feel free to to try and test it in ways other than the example below. 
**TESTING INSTRUCTIONS:**
1. Add a state with a display text for the Game Wide state
2. Add another state below
3. Add a connection between the two states
4. Add a transition to the connection
5. For any scope create a sequence button press or text entry.
6. Try to create the same exact sequence or text entry again
7. Should receive error message about duplicate

**Comment by mmicciolo** [comment]
Hello @franciscastro @sai-educ @geseiche @IvonArroyo 

This issue is ready for testing on https://dev.wearablelearing.org

In the comment above I have posted testing instructions.

Please post a comment here with the results of your testing.

**Comment by sai-educ** [comment]
Tried several times but did not receive any error message. Waiting for others to test.

**Comment by geseiche** [comment]
Tested. Received the error for both the color sequence and the text entry. Also confirmed that text entry will confirm the duplicate when the cases of the two text entries are different. 

@sai-educ Did you set yours up like this?
![image](https://user-images.githubusercontent.com/32133509/135611672-f0d7a7d6-8f4e-48a1-b51b-4411eb7a5840.png)

**Comment by mmicciolo** [comment]
@sai-educ make sure you are adding duplicate sequences in the same scope. eg two red sequences in the game wide scope.

**Comment by sai-educ** [comment]
Thanks, @geseiche for the visual. Tested again and this is working as intended. Received error for both color sequence and text entry.

**Comment by mmicciolo** [comment]
Testing complete. Closing.
