### ISSUE TITLE
Fixing bugs with timer transition

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#133]

**Comment by mmicciolo** [comment]
This issue enhances the delay/timer transition functionality. In the transition editor both a delay/timer are classified as a Timer. However, depending on if it is used by itself or with another transition type determines if it is a delay or a timer.

The Timer configuration dialog looks the same for either delay/timer. If its used with other transition types in the same scope determines if it acts like a delay or timer.
![image](https://user-images.githubusercontent.com/23061418/142771894-d64dc393-dc8b-4159-ade1-b0c7a24ee689.png)

Delay - Used by itself without any other transition type for a given scope 
![image](https://user-images.githubusercontent.com/23061418/142772155-c3eb32a3-24db-4836-9a24-fddba52c47b1.png)

Timer - Used as a "secondary transition" along side a single button press, sequence button press, keyboarding input. It provides a way to setup time limits on certain tasks.
![image](https://user-images.githubusercontent.com/23061418/142772146-8d27911e-4c8d-455a-bca5-9fb2642c78a6.png)

Below is an example of how to test this. Please feel free to to try and test it in ways other than the example below.

**Comment by mmicciolo** [comment]
Hello @franciscastro @geseiche @sai-educ @IvonArroyo

This issue is ready for testing on https://dev.wearablelearning.org

**Comment by franciscastro** [comment]
### Tested the **Delay** setup 
**Result:** No problem found (see screenshot 1 and 2)

Screenshot 1: Delay setup -- move to next state after 3 seconds
<img width="1200" alt="Screen Shot 2021-11-22 at 10 54 24 AM" src="https://user-images.githubusercontent.com/1910413/142893128-35f013a6-51bf-4a05-b75a-b7231fb57c46.png">

Screenshot 2: Debugging the delay setup
<img width="910" alt="Screen Shot 2021-11-22 at 10 51 16 AM" src="https://user-images.githubusercontent.com/1910413/142895776-ac1dad3f-9722-4b8c-a999-d3cc6b31b2a3.png">

### Tested the **Timer** setup 
**Result:** Bug found (see screenshot 3 to 6)
**Bug description:** You can only debug the timer on the first-ever attempt to debug. On succeeding attempts, it stays on the first state no matter how long you wait for the timer to expire.

Screenshot 3: Timer setup -- move to default state after 3 seconds
<img width="1200" alt="Screen Shot 2021-11-22 at 10 54 24 AM" src="https://user-images.githubusercontent.com/1910413/142896586-5cb9dd93-14b6-4cb3-9209-c8ef3f4fe1b0.png">

Screenshot 4: Debugging the timer setup
<img width="1429" alt="Screen Shot 2021-11-22 at 11 17 50 AM" src="https://user-images.githubusercontent.com/1910413/142897255-83f21db5-3cb3-4261-86b9-f01a5a263a31.png">
<img width="1428" alt="Screen Shot 2021-11-22 at 11 17 25 AM" src="https://user-images.githubusercontent.com/1910413/142897309-7e96346c-9d8e-462d-91b9-fd88ea2f463c.png">

**Comment by geseiche** [comment]
Tested and works as expected!

**Comment by apoh3** [comment]
**Delay** test passed.

**Timer** test did not pass.
![image](https://user-images.githubusercontent.com/61091501/144446489-7cd5089c-e97d-4b1b-99de-be723376007e.png)
Left transition is Button Press (Red). Right transition is Timer (3s). I am not being transitioned to the right state after waiting a minute. 
![image](https://user-images.githubusercontent.com/61091501/144446702-d8a013a9-2d28-4498-8306-02933b5495b5.png)

**Comment by mmicciolo** [comment]
Moving back to development to fix found issues.

**Comment by mmicciolo** [comment]
Bug has been fixed and is ready for retesting.

**Comment by sai-educ** [comment]
**Both Delay and Timer working as intended.** However, while testing for Timer, I was hoping to see an indication of countdown - as for game players may not realize they have a limited amount of time. My set up below - 

Delay setup - 
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/25312586/146998172-1a09c081-766a-47f3-a5c3-653f95ec62c8.png">


Countdown is visible -
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/25312586/146998008-9139331a-4471-4455-bf56-3cdab36b0eb3.png">

Timer setup with 3 States (2 button press transitions and one timer transition) - 
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/25312586/146998650-bf909761-e445-4e5a-bd8e-fd718ca80860.png">

Output when no button is pressed -
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/25312586/146998721-f04175b3-d957-4752-8120-9a79d4b33905.png">

Output when either button1 or button2 is pressed -
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/25312586/146998811-53ad61c3-432a-4878-8590-bd55874c51f6.png">

**Comment by mmicciolo** [comment]
Hello @sai-educ 

Thank you for your feedback. I agree that there should be a countdown for a timer like there is for delay.

I will make the change and report back here for retesting.

**Comment by mmicciolo** [comment]
Hello @sai-educ 

I added a countdown display.

Ready for testing at : https://dev.wearablelearning.org

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
