### ISSUE TITLE
Fixing bugs with random transition

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#134]

**Comment by mmicciolo** [comment]
This issue enhances the random transition functionality.
Below is an example of how to test this. Please feel free to to try and test it in ways other than the example below.

**Comment by mmicciolo** [comment]
Hello @franciscastro @geseiche @sai-educ @IvonArroyo

This issue is ready for testing on https://dev.wearablelearning.org

**Comment by franciscastro** [comment]
### Tested the Random transition setup

**Result:** No problem found (see screenshots)

Screenshot 1: Random transition setup
<img width="1425" alt="Screen Shot 2021-11-22 at 11 48 56 AM" src="https://user-images.githubusercontent.com/1910413/142902661-f7fb4127-2a7a-471c-b285-ca4056302da6.png">

Screenshots 2-5: Debugging the random transition setup
<img width="1427" alt="Screen Shot 2021-11-22 at 11 51 03 AM" src="https://user-images.githubusercontent.com/1910413/142902909-b317982e-f86d-4aa1-8a34-01b00ea6d990.png">
<img width="1428" alt="Screen Shot 2021-11-22 at 11 53 47 AM" src="https://user-images.githubusercontent.com/1910413/142903089-2dc7eb22-fe48-488e-87e5-c04279d47683.png">
<img width="1428" alt="Screen Shot 2021-11-22 at 11 51 57 AM" src="https://user-images.githubusercontent.com/1910413/142903031-112a0570-0d5a-43b1-9ed1-aca253be341d.png">
<img width="1428" alt="Screen Shot 2021-11-22 at 11 51 19 AM" src="https://user-images.githubusercontent.com/1910413/142902982-f63bfc9f-3b6a-4422-b556-9533b0c0fc2e.png">

**Comment by apoh3** [comment]
Test passed. 
Out of 15 runs, transitioned to 1st state 7 times, 2nd state 4 times, and 3rd state 4 times.

**Comment by sai-educ** [comment]
No issues found. Performed multi-level random transition (setup below) and system works as intended.
![Screenshot 2021-12-07 at 19-14-22 wlcp-ui](https://user-images.githubusercontent.com/25312586/145125747-7925c492-9380-4a1b-ab04-4ae213e5ae85.png)

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
