### ISSUE TITLE
Add Warning for Connections without Transitions

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#139]
A common mistake in the editor is forgetting a transition on a connection. Theoretically, all connections should have transitions on them with the exception of the connection from the start state to the first state. 

Add a pop up warning either at save or at debug if there is a connection that does not have a transition telling the programmer that this will result in the state being skipped.

**Comment by mmicciolo** [comment]
Closing as I am merging this issue with #173
