### ISSUE TITLE
Game Editor: NOT allowing a transition from start state

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#14]
We should not allow to drag a transition on the first arrow for any arrow leaving from the start state.

In fact, Start state should say "start here" not "start state", as otherwise there is an expectation that it should behave as all the other states.

**Comment by mmicciolo** [comment]
Fixed. Can no longer place transitions on connections coming from start state. An error message is now displayed.
