### ISSUE TITLE
Add indication whether state/transition filled

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#140]
Programmers who like to lay out all the states before filling them in often have a hard time remembering if they have set the data in a state or transition. This leads to them getting error messages that they do not understand.

Add some sort of indicator for whether a state/transition has content. (i.e. a state has display text/image and a transition has a type selected and content set). Maybe this could be in the form of a color change or a notification icon on the element.

This would also help indicate to the programmer what states/transitions were reset if revalidation occurs.

**Comment by IvonArroyo** [comment]
I think this is a great idea, like an exclamation sign that indicates
empty! or something like that.

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst

Pronouns: She/Her

**Comment by mmicciolo** [comment]
Closing as I am merging this issue with #173
