### ISSUE TITLE
Why are connections separate from transitions?

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#141]
Other than from the start to the first state, is there any instance where a connection should not have a transition. Is there a reason why we keep them as two separate units instead of combining them? (i.e. when drawing a connection, a transition would automatically be placed)

**Comment by mmicciolo** [comment]
One use case would be when we have variables implemented. You may want to fly through a few states without any interruption from transition to init any variables and perform any pre game routines / calculations. Going to close unless there is any further comments.
