### ISSUE TITLE
Errors in Console when double clicking on states or transition 

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#142]
Hi Matt,

I made a small program, called MyTest for user iarroyo/iarroyo. It uses random variables and delays.

I found several times in the process that suddenly I couldn't double click and open a transition or a state. I checked the console and I saw a lot of red errors. I attach the console screenshot.

![image](https://user-images.githubusercontent.com/5631787/130098966-a2465408-e257-4d4f-a473-eb284683424e.png)

**Comment by mmicciolo** [comment]
Closing due to the fact this is a duplicate of #115 

It is related to a bigger issue and all further progress will be tracked in #115
