### ISSUE TITLE
Copy + rename remove a-z only message

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#144]

**Comment by mmicciolo** [comment]
This issue removes the a-z only limitation on copy + rename. Below is an example of how to test this. Please feel free to to try and test it in ways other than the example below.
TESTING INSTRUCTIONS:
1. Load a game (preferably a test one you created with some test data)
2. Copy the game. For the name using some that is not a-z limited. Verify you are not limited to a-z only and verify that you don't receive any a-z only error messages.
3. Repeat step 2 for rename

**Comment by mmicciolo** [comment]
Hello @franciscastro @sai-educ @geseiche @IvonArroyo

This issue is ready for testing on https://dev.wearablelearning.org

In the comment above I have posted testing instructions.

Please post a comment here with the results of your testing.

Thanks!!

**Comment by sai-educ** [comment]
Works as intended. This is good to go.
