### ISSUE TITLE
Split Name Duplicate from Error Message Create/Copy/Rename

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#146]
Add separate functionality to check if game names are duplicates. Create related error messages. This will separate more serious errors from errors with the game name. Related issue #130 

Related Platform Messages
gameEditor.create.error
gameEditor.rename.error
gameEditor.copy.error

**Comment by mmicciolo** [comment]
Closing b/c merging with #153
