### ISSUE TITLE
gameEditor.state.filledScope appears on state not transition

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#147]
filledScope message should appear on the TRANSITION when all button press options for all players have already been assigned in neighboring transitions. However, when this occurs, the gameEditor.inputTransition.emptyState message appears on the transition and the filledScope message appears on the state

Steps to recreate:
1. Create a game
2. Add a state below the start and fill in the content
3. Add two states below with transitions
4. In the left transition, select all the button color options under game wide and save
5. Now on the right transition if you double click to open, it gives gameEditor.inputTransition.emptyState = Fill in the state above to edit this transition
6. When you double click on the state below the right transition, it gives gameEditor.state.filledScope = All players and teams have been assigned in neighbor states.

It would make more sense if the filledScope message showed when clicking the right transition since the current message is false

**Comment by mmicciolo** [comment]
With all 4 single button presses checked in the left transition, clicking on the right transition throws the gameEditor.state.filledScope message now. Clicking on the right lower state also throws the gameEditor.state.filledScope message.

![image](https://user-images.githubusercontent.com/23061418/147400958-90e70dc5-868f-437d-bfdc-e9775c86d155.png)

Pushing + Deploying to dev!

**Comment by geseiche** [comment]
@mmicciolo Testing script ready for approval

**Comment by mmicciolo** [comment]
Approved!

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by franciscastro** [comment]
**Test Scenario:** 3 Output States, 2 Transitions -- Top Output State is filled (text display), Left Transition filled as described in the testing script (button press, all options), Right Transition empty

**Results:**
- Functional -- The correct error message is displayed as described in the test script (see screenshot below)

**Screenshots:**

<img width="644" alt="Screen Shot 2022-03-01 at 12 48 30 PM" src="https://user-images.githubusercontent.com/1910413/156221928-5f1d22a5-6597-4ab5-a054-8f1f193967a7.png">

---

**Open question:**

Should the same message be displayed when all states and transitions are empty?  The same message is currently being displayed when ALL states and ALL transitions are empty or have not yet been set (see screenshot below)

CC: @geseiche @mmicciolo 

<img width="698" alt="Screen Shot 2022-03-01 at 12 46 33 PM" src="https://user-images.githubusercontent.com/1910413/156222148-578e5aa0-c1b4-461c-9ff9-c903ecb071cc.png">

**Comment by sai-educ** [comment]
The correct error message is displayed as described in the test script. 

One suggestion is to consider making this label more user friendly such as: "Oops! You cannot edit this Transition as you have selected all buttons in another Transition. Go to the other Transition, uncheck at least one button. Come back to this Transition to continue." 

![Screenshot 2022-03-01 at 16-28-20 wlcp-ui](https://user-images.githubusercontent.com/25312586/156252044-e55058ae-533a-40aa-b0c8-f7707b142d7d.png)

**Comment by apoh3** [comment]
@franciscastro @mmicciolo 

**Test passed**

Following same FSM as @geseiche I receive the correct error message for the right transition:
![image](https://user-images.githubusercontent.com/61091501/156427002-96af7bc2-0f68-4d10-a36d-2d98f76ac60a.png)

Also tested the following scenario and received the correct error message:
![image](https://user-images.githubusercontent.com/61091501/156427484-620a8339-cf4b-410c-9e69-968129bc693e.png)
![image](https://user-images.githubusercontent.com/61091501/156427509-a7bd71d9-2572-4a75-80a3-4023f6e945a4.png)

**Comment by apoh3** [comment]
@franciscastro @mmicciolo @sai-educ @geseiche @apoh3 @IvonArroyo 
All tests closed.

For any open questions please create a new ticket.
