### ISSUE TITLE
Add Button To Random Transition

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#148]
Instead of random transition transitioning automatically the user will now have to push a button to transition. This gets rid of the "dummy state problem"

**Comment by mmicciolo** [comment]
This issue adds a button the game player for random transition type. This way the transition doesn't happen automatically and requires a button press to continue on. This is to stop the need of a dummy state in order to accomplish the same thing. Below is an example of how to test this. Please feel free to to try and test it in ways other than the example below.

TESTING INSTRUCTIONS:

1. Create a test game with 2 states, 2 connections and 1 transition
2. Fill the states with some test data
3. Enable random on the transition.
4. Run & Debug and verify a button appears when on the random transition

**Comment by mmicciolo** [comment]
Hello @franciscastro @geseiche @sai-educ @IvonArroyo 

This issue is ready for testing on https://dev.wearablelearning.org

**Comment by franciscastro** [comment]
### Tested the Random Transition Button

**Result:** The button appears when run on debug mode (see screenshot -- _Note: This is the same screenshot from my testing of issue #134 _)

Screenshot:
<img width="1427" alt="Screen Shot 2021-11-22 at 11 51 03 AM" src="https://user-images.githubusercontent.com/1910413/142903811-f5dcdacd-c2ab-43ac-8cc3-c5cd21812202.png">

**Comment by apoh3** [comment]
Test passed.
Button appears and works.

**Comment by sai-educ** [comment]
Working as expected. Button appears during random transition.

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
