### ISSUE TITLE
Canceling dialogs does not clear out fields

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#149]

**Comment by mmicciolo** [comment]
Check the following:

- New
- Load
- Save
- Copy
- Rename

**Comment by mmicciolo** [comment]
While working on this issue I am also fixing an issue with most modern browsers which is the credential manager. It can get in the way when trying to enter usernames and passwords, so I have set all fields to type=text and am changing the font of the password field to show the black circles to conceal the password.

**Comment by mmicciolo** [comment]
This issue is complete.

Pushing & deploying to dev.

**Comment by franciscastro** [comment]
@apoh3 will be writing the test script for this, with @mmicciolo reviewing for coverage

**Comment by apoh3** [comment]
@mmicciolo testing script ready for review:

All dialogs within the platform need to be tested. Below are examples of tests. Please feel free to try and test it in ways other than the example below.

### **Testing Login**
1. Select Login
2. Complete **Username and Password** fields
3. Select Back
4. Select Login
5. Make sure Username and Password fields are cleared
### 
1. Select Login
2. Select **Register**
3. Complete all fields
4. Select Cancel
5. Select Register 
6. Make sure all fields are cleared
### 
1. Select Play a Game!
2. Enter a **Game PIN**
3. Select Home
4. Select Play a Game!
5. Make sure all fields are cleared
### 
1. Make sure you have a valid Game PIN
2. Select Play a Game!
3. Enter a valid Game PIN
4. Select Join
5. Complete **Player name**
6. Select Home
7. Select Play a Game!
8. Enter the valid Game PIN again
9. Select Join
10. Make sure the Player name field is cleared
### 
1. Make sure you have a valid Game PIN
2. Select Play a Game!
3. Enter a valid Game PIN
4. Select Join
5. Complete Player name
6. Select Continue
7. Select a **team/player** that is not the default (not Team 1 Player 1).
8. Select Home
9. Repeat above steps until you arrive at Team/Player dialog.
10. Make sure drop down has reverted to default (Team 1 Player 1).


### **Testing Game Manager**
1. Select **Start Game**
2. Select any game under **Your Games**
3. Select Cancel
4. Select Start Game
5. Make sure drop down is cleared
### 
1. Select **Start Game**
2. Select any game under **Public Games**
3. Select Cancel
4. Select Start Game
5. Make sure drop down is cleared


### **Testing Game Editor**
1. Select **New**
2. Complete **Game Name**
3. Select Cancel
4. Select New
5. Make sure Game Name field is cleared
### 
1. Select **Load**
2. Complete **Search field**
3. Select Cancel
4. Select Load
5. Make sure Search field is cleared
### 
1. Select **Load**
2. Select any game under **Public Games**
3. Select Cancel
4. Select Load
5. Make sure Public Games has no selected game
### 
1. Select **Load**
2. Select any game under **Your Games**
3. Select Cancel
4. Select Load
5. Make sure Your Games has no selected game
### 
1. Open an existing game
2. Select **Save**
3. Complete all fields
4. Select Cancel
5. Select Save
6. Make sure all fields are cleared
### 
1. Open an existing game
2. Select Game Options
3. Select **Copy Game**
4. Complete all fields
5. Select Cancel
6. Select Game Options
7. Select Copy Game
8. Make sure Enter a new name field is cleared
### 
1. Open an existing game
2. Select Game Options
3. Select **Rename Game**
4. Complete all fields
5. Select Cancel
6. Select Game Options
7. Select Rename Game
8. Make sure all fields are cleared
### 
1. Open an existing game
2. Add a **new State** and connect it to the existing game
3. Select the new State
4. Change the State Title
5. Select Cancel
6. Select the new State
7. Make sure the State Title has reverted to State
8. Repeat above to continue checking the following dialogs within the State Editor:
- Display Text input field
- Display Photo input field
- Play Sound input field
- Play Video input field
- Modify Global Variable fields


### **Testing Game Player**
1. Same tests as those for Play a Game! dialogs under Testing Login.

**Comment by mmicciolo** [comment]
Approved! Thank you for the thorough test cases @apoh3

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by sai-educ** [comment]
Login scenarios work as intended, except for player selection drop down menu does not revert to default "Team 1 Player 1". Need additional testers to confirm. @franciscastro @geseiche @apoh3  

![191](https://user-images.githubusercontent.com/25312586/156238143-e9f0155b-cc31-4d2c-98ca-5b5b6e379527.gif)

All Game Manager, Game Editor and Game Player scenarios working as expected.

**Comment by geseiche** [comment]
**Test Passed Except**
As noted by @sai-educ, the player selected is not cleared. This is true for both logged in and no log in game playing.

I tested both types of Login, the Manager, and the Editor (including loading, saving, settings, states, transitions, and variables)

**Unrelated Bug** - Wrong Error Thrown
Steps to Recreate
1. Click "Play a game!"
2. Enter a valid game pin
3. On the Enter Name screen, leave the box blank and click continue. 
The following message is shown
![image](https://user-images.githubusercontent.com/32133509/156896508-63364fa1-2995-4b4d-a0e8-a06fc540380c.png)
This is incorrect. The message should say something like "Please enter a name" 

**Enhancement** - Load Selection Not Indicated
Steps to Recreate
1. Enter the game editor
2. Click Load
3. Click a specific game
Once a game is clicked on, it should be highlighted so the user can see which game they clicked on

**Comment by mmicciolo** [comment]
@sai-educ I have fixed the bug with the player selection not clearing out.

@geseiche I have moved your unrelated bug finding to new issues.

**Comment by apoh3** [comment]
**Tests passed**

All tests from the original test case still pass. The player selection drop down menu now does revert to default "Team 1 Player 1" (referring to @sai-educ's comment)

**Comment by sai-educ** [comment]
**Tested again. All tests working as intended.**

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
