### ISSUE TITLE
Saving and Loading Improvements (Manual & Auto) + WYSIWYG update

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#150]
A new save + load system needs to be implemented.

It will work as follows:
1. Each save will require a description
2. When loading you can select the most recent or from a history of saves
3. Auto save will happen every X minutes and will save to a different history of auto saves.
4. Add db create statement to docker

**Comment by mmicciolo** [comment]
Remaining tasks:
1. i18n
2. Cleanup UI
3. Search
4. Auto save

**Comment by mmicciolo** [comment]
Finished:
1. i18n
2. Cleanup UI
3. Search

Now working on auto save. Need to create a very basic event system for the following events:
add state
add connection
add transition

edit state
edit transition

move state

delete state
delete connection
delete transition

**Comment by mmicciolo** [comment]
This item still needs a lot of work before it is ready. I am going to be changing how the system works too a bit after our last meeting on Monday 11/22.

Before: We had 2 different saves. Manual save + auto save. Manual save required the user to click the button and input description. Auto save happened on 9 state/transition/connection events in the comment above. When loading there was a separate drop down for manual and auto saves.

Now: Still have both save types but the load dialog will display them all in one list. Manual saves (where you enter a description) will show up as "tagged" with the description.

**Comment by mmicciolo** [comment]
In our 12/29 meeting we all agreed on how I was going to go about finishing up implementing this feature.

Today (12/18) I have begun working on the feature again.

I am creating a new branch for the feature called feature/wlcp-150. All progress with be put in that branch from here on out.

**Comment by mmicciolo** [comment]
Experimenting with bare bones WYSIWYG (What You See Is What You Get) UI. Before buttons used to be greyed out and when a game wasn't loaded the states / transitions could not be dragged. The thought around this is why show it if you can't use it. In this case remove it if you can't use it. 

When you first come into the editor the toolbox is blank and the only buttons available are new and load.

When a game is loaded new buttons like save, run & debug and game options appear as well as the toolbox.

**Comment by mmicciolo** [comment]
Starting a new TODO list:

- i18n
- Add debug & copy functionality to archive viewer
- Revert to on history popout

**Comment by mmicciolo** [comment]
Ready to merge into dev.

**Comment by franciscastro** [comment]
> Experimenting with bare bones WYSIWYG (What You See Is What You Get) UI. Before buttons used to be greyed out and when a game wasn't loaded the states / transitions could not be dragged. The thought around this is why show it if you can't use it. In this case remove it if you can't use it.
> 
> When you first come into the editor the toolbox is blank and the only buttons available are new and load.
> 
> When a game is loaded new buttons like save, run & debug and game options appear as well as the toolbox.
> 
> Toolbox is now split up into tools you drag and tools you click.
> 
> You can load a save from the history. Archived game is loaded in read only mode so the toolbox is removed and a red banner displayed. The only option is to go back (to the latest version).
> 
> https://drive.google.com/file/d/1QhEtVBThf5gkhQ8Z0YnAsAyq9WtAZ6sh/view?usp=sharing
> 
> ![ui](https://user-images.githubusercontent.com/23061418/146716876-d49b84e6-9e35-4704-8975-c7aa6c127763.gif)

@mmicciolo  Should this be in a separate issue ticket?

**Comment by mmicciolo** [comment]
@franciscastro No separate issue the WYSIWYG has already been fully implemented. I was just tracking my progress in this issue.

**Comment by franciscastro** [comment]
> @franciscastro No separate issue the WYSIWYG has already been fully implemented. I was just tracking my progress in this issue.

@mmicciolo  Okay, I'll update the title to reflect that just so the team can find it easily later on. Thanks!

**Comment by mmicciolo** [comment]
This is a two part issue.

**Part 1 : What you see is what you get UI (WYSIWYG)**

The game editor interface has been redesigned to only show buttons and toolbars that you can use at a given time.

When you first open up the editor you are only presented with actions you can accomplish such as create a new game or load and existing game. Before we showed all of the buttons but greyed them out to make them no usable. Now we simply don't display them.

![image](https://user-images.githubusercontent.com/23061418/154731414-750531cd-b88b-4096-add9-f2e3018935da.png)

Creating a new game or loading one displays the draggable and clickable toolbox and adds more buttons to the main toolbar at the top.

![image](https://user-images.githubusercontent.com/23061418/154731553-736af1a2-6c08-4437-8ab9-574f99e041da.png)

This is UI style is used throughout the entire game editor.

**Part 2 : New loading / saving / auto save interface**

This issue adds a "google doc style" auto save and history interface.

For any of the following actions a auto save is made and show under the history button:

add state
add connection
add transition

edit state
edit transition

move state

delete state
delete connection
delete transition

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @geseiche @IvonArroyo @sai-educ 

Ready for testing!

This item has already thoroughly been tested by the ERSP team but we can still do some brief testing.

**Comment by apoh3** [comment]
**Tests Passed**

**Part 1 : WYSIWYG Passed**

**Part 2 : New loading / saving / auto save interface Passed**
![image](https://user-images.githubusercontent.com/61091501/160819299-e42bd87d-cbd1-4879-a5f1-ccabb3d1b475.png)
![image](https://user-images.githubusercontent.com/61091501/160817595-059be5a9-477d-46b7-8936-32682b333fe8.png)
![image](https://user-images.githubusercontent.com/61091501/160817801-4f9d36c8-2b77-4056-83a6-65c8f14e8339.png)

**Comment by sai-educ** [comment]
**Tests passed.** 

- WYSIWYG UI - Editor only displays actions that users need
- Game History log

<img width="202" alt="Screen Shot 2022-03-30 at 2 05 35 PM" src="https://user-images.githubusercontent.com/25312586/160902388-55458225-f362-445f-9d01-675f259d9984.png">

**Comment by mmicciolo** [comment]
Testing complete.
