### ISSUE TITLE
Docker Dev Config

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#152]
A new docker dev config needs to be added so that a separate master and dev db can run.

**Comment by franciscastro** [comment]
Follow-up: This includes updates to the Spring Boot config files --

Proposed having 2 separate setups for docker-compose: one for dev, one for live

Also includes the creation of config files for the Spring Boot project 
- application-ecs
- application-docker
- application-docker-dev

**Comment by mmicciolo** [comment]
@IvonArroyo @franciscastro @apoh3 @sai-educ @geseiche 

Not requiring full team testing as this is a small fix related to an internal tool.

Testing complete.

Closing.
