### ISSUE TITLE
wlcp-api contact form api end point

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#154]
Add a REST endpoint on the wlcp-api microservice for a contact form on the main website to post data to.
http://preview.wearablelearning.org/#contact

**Comment by mmicciolo** [comment]
Endpoint merged into dev and deployed to dev.

**Comment by franciscastro** [comment]
@mmicciolo @geseiche @sai-educ I think this needs to be moved back to In progress given our discussions on Slack on identifying potential problems sources and alternative solutions?

**Comment by mmicciolo** [comment]
@franciscastro @geseiche  @sai-educ  I have moved this back to in progress. We need to fix this issue by implementing a nonce that needs to sent almost with the contact form.

**Comment by mmicciolo** [comment]
Closing issue. This has been implemented using google forms now due to spam issues.
