### ISSUE TITLE
Random Code Appearing on Game Load Dialog

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#159]
![image](https://user-images.githubusercontent.com/32133509/139737227-4db01c3a-2130-4d4b-8bbc-7d0aa0c5abc3.png)

**Comment by geseiche** [comment]
on dev server

**Comment by mmicciolo** [comment]
This will be fixed in the new saving & loading feature.

**Comment by mmicciolo** [comment]
This was a bug in the UI5 library that has been fixed. Closing this issue. Also new load / save will make this obsolete anyway.
