### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#160]

**Comment by mmicciolo** [comment]
Change the wording of the operators over the variables to these new names:

= Set to
+= Increase by
-= Decrease by
*= Multiply by
/= Divide by

**Comment by mmicciolo** [comment]
- Copy/rename/delete
- Switch wording of operators above

**Comment by franciscastro** [comment]
@mmicciolo Given your last comment on the TODOs for this issue, should this be moved back to In Progress?

**Comment by mmicciolo** [comment]
@franciscastro I am probably going to open a new issue for game variable improvements. This issue focused on getting the core code into the dev branch.

**Comment by mmicciolo** [comment]
Closing. Will open new issues for global variable features.
