### ISSUE TITLE
Virtual Device Sequence Button Press Click Instead of Drag

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#162]
This is an update to the color sequence interactions. Instead of dragging colors to create a sequence, the colors are now clickable buttons and the user clicks a color to add the color to the sequence being generated. The goal for this update is to improve usability of the color sequence interaction.

**Comment by franciscastro** [comment]
@geseiche will be writing the test script for this, with @mmicciolo reviewing for coverage

**Comment by geseiche** [comment]
@mmicciolo Testing script ready for approval

**Comment by franciscastro** [comment]
**Test Scenario:** Testing from Game Editor

**Results:**
- Functional -- I am not able to drag the colors into the color sequence box
- Functional -- Colors are added to the color sequence box when clicked
- Functional -- The color sequence box adjusted size upon adding beyond 4 colors into the color sequence box

**Screenshots:**

<img width="904" alt="Screen Shot 2022-02-22 at 10 13 37 PM" src="https://user-images.githubusercontent.com/1910413/155256194-a55c24fc-f858-430b-8222-1cb2886e92b6.png">

---

**Test Scenario:** Player Mode (via the Debugger)

**Results:**
- Functional -- I am not able to drag the colors into the color sequence box
- Functional -- Colors are added to the color sequence box when clicked
- Functional -- The color sequence box adjusted size upon adding beyond 4 colors into the color sequence box

**Screenshots:**

<img width="751" alt="Screen Shot 2022-02-22 at 10 17 40 PM" src="https://user-images.githubusercontent.com/1910413/155256377-9e1d6594-7e0c-43cd-81b5-77c4f3eafa71.png">

**Comment by mmicciolo** [comment]
Approved! Thank you for beginning the testing @franciscastro !

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by apoh3** [comment]
**Test passed**

In Transition Editor, when attempting to drag a block, the cursor becomes a not-allowed cursor and no dragging occurs. Clicking blocks does work and sequence box size adjusts to fit more blocks when needed. Same results in Run and Debug.

**Comment by sai-educ** [comment]
Test passed. New color sequence functionality working as expected.

**Comment by apoh3** [comment]
@franciscastro @mmicciolo @sai-educ @geseiche @apoh3 @IvonArroyo 
All tests complete.
