### ISSUE TITLE
Transition and state editor dialog elements are inaccessible after browser window resize

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#166]
**Description:**
Certain elements in the transition editor become inaccessible after the browser is reduced in size

**Replicate:**
1. Create a game such that you're able to add a transition
2. Open up the transition editor 
3. Reduce the width size of the browser window -- some elements in the transition editor window become inaccessible after this (see screenshot)

**Additional info:**
<img width="1196" alt="Screen Shot 2021-11-22 at 11 14 58 AM" src="https://user-images.githubusercontent.com/1910413/142899613-8d14aae0-5065-4de4-aa3b-b2ee6f221f2f.png">
:

**Comment by mmicciolo** [comment]
This happens for output state dialog as well. Working on fix.

**Comment by franciscastro** [comment]
@apoh3 will be writing the test script for this, with @mmicciolo reviewing for coverage

**Comment by apoh3** [comment]
@mmicciolo testing script ready for review:

When resizing the web browser, the Transition Editor elements become not visible. To fix this, scrolling capabilities were added to the Transition Editor when the browser screen size is smaller than the default Transition Editor size. 

![image](https://user-images.githubusercontent.com/61091501/152549058-375d0e1f-a44a-468d-a690-188574ed456a.png)


Below is an example of how to test this. Please feel free to try and test it in ways other than the example below.

### **Browser Resize: Max Size to Smaller**
1. Have your web browser open to maximum size.
2. In the Game Editor, open a game (whether new or loaded) and add a new transition.
3. Open the Transition Editor.
4. Resize your web browser to a smaller size.
5. Check if all Transition Editor elements are accessible via scrolling.
6. Repeat steps 4 and 5, testing multiple web browser sizes.
### 
### **Browser Resize: Small to Max Size**
1. Have your web browser open to less than maximum size.
2. In the Game Editor, open a game (whether new or loaded) and add a new transition.
3. Open the Transition Editor.
4. Resize your web browser to maximum size.
5. Check if all Transition Editor elements are accessible.

**Comment by franciscastro** [comment]
> This happens for output state dialog as well. Working on fix.

@apoh3 As mentioned by @mmicciolo above, this also happens for output states. Can you update the test script to also include that? I'll update the title of this ticket to reflect it as well.

**Comment by mmicciolo** [comment]
Approved!

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by sai-educ** [comment]
**Test passed.** Transition Editor and State Editor - both accessible via scrollbars in browser resize tests. @franciscastro @mmicciolo @geseiche @apoh3 Need one more tester to confirm.

Transition Editor -

https://user-images.githubusercontent.com/25312586/156246434-e3080fef-85ca-4df4-a17c-83ef579d3453.mp4

State Editor -

https://user-images.githubusercontent.com/25312586/156246472-6bcc5fa2-ad9d-4d40-a905-9ee4818b1656.mp4

**Comment by geseiche** [comment]
**Test Passed**

All aspects of both state and transition editors are visible at max and min screen size with one horizontal scroll bar and one vertical scroll bar.

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
