### ISSUE TITLE
Updates to History Load feature

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#168]
This issue addresses proposals for the History Load feature

1. Title with name of game changes color to indicate that the game being shown is currently just in view mode
2. Change the menu buttons to Back, Copy, Revert to
3. Grey out the tool box to indicate that the game being shown is currently just in view mode

**Comment by mmicciolo** [comment]
All updates will be posted in #150

**Comment by mmicciolo** [comment]
Latest update : https://github.com/wearable-learning-cloud-platform/wlcp-issues/issues/150#issuecomment-997611950

**Comment by mmicciolo** [comment]
Closing. All progress will be recorded in #150
