### ISSUE TITLE
Spring Boot 2.6.2 Upgrade + Update & Rebuilt Jenkins Instance

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#174]
Upgrade all spring boot microservice applications to 2.6.2.
Upgraded jenkins instance to

**Comment by mmicciolo** [comment]
Upgrade all spring boot microservice applications to 2.6.2.
Upgraded jenkins instance to

**Comment by franciscastro** [comment]
@mmicciolo Does this include updates to the Spring Boot config files? From a previous conversation, you proposed having 2 separate setups for docker-compose: one for dev, one for live, including the creation of config files for the Spring Boot project (application-ecs, application-docker, application-docker-dev)

**Comment by mmicciolo** [comment]
@franciscastro No that is issue #152
