### ISSUE TITLE
startDebugGameInstance Thread.Sleep Bug

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#175]
Years ago I had written some very poor code that used a Thread.Sleep method call in order to time it correctly and make it work.

The timer was set to wait 500ms. In some cases this isn't enough and when you click run and debug it can cause an exception to be thrown. This is because the GameInstanceController calls service.start() which starts up the game instance and creates and entry in the game instance table. This takes time so a manual sleep was added so that this entry could be populated so that the game instance id (which is auto generated) could be returned in the response body.

Now I have added a while loop to continuously poll to see when the variable is populated and not null anymore. Not perfect but better.

![image](https://user-images.githubusercontent.com/23061418/147373157-6c91fbb0-0fc3-42b5-bea1-1fa274236510.png)

**Comment by franciscastro** [comment]
@sai-educ will be writing the test script for this, with @mmicciolo reviewing for coverage

**Comment by mmicciolo** [comment]
Hello @sai-educ 

This issue had to do with a bug that when you would start a game in the game manager or run & debug in the game editor, sometimes starting the game would fail and throw an exception because the game instance id wouldnt be populated (which the call had to reutrn).

This was because I was using a hard coded sleep to delay the code and sometimes that sleep wasnt long enough.

Instead I switched over to using a while loop that waited for the game instance id field to be populated before returning to the client.

You can test this by starting a few game instances in the manager and making sure no exceptions are thrown and starting a few run and debug instance in the game editor.

**Comment by sai-educ** [comment]
Test script:

Game Manager - 
1. Login to dev system from [here](https://dev.wearablelearning.org/wlcp-ui/index.html)
2. Open Game Manager
3. Click State Game >> start any game (private or public)
4. Success if there are no errors

Game Editor -
1. Open Game Editor from dev system
2. Create/load any game
3. Click Run and Debug 
4. Success if there are no errors

I believe this is already working as expected as we are actively performing this task during our play testing. 

@franciscastro @mmicciolo @apoh3 @geseiche Please confirm.

**Comment by mmicciolo** [comment]
@IvonArroyo @franciscastro @apoh3 @geseiche @sai-educ

Test case approved!

**Comment by geseiche** [comment]
Tests passed. No issues.

**Comment by apoh3** [comment]
**Tests passed.**

No errors thrown.

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
