### ISSUE TITLE
Disallow text highlighting for the game title + new/load instructions

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#177]
This issue is meant to disallow highlighting of the text for the game title and initial instructions in the toolbox when you first come into the editor.

Sometimes the text can get accidentally highlighted when scrolling.

**Comment by franciscastro** [comment]
@mmicciolo What issue does this address again? There's no description in the ticket

**Comment by mmicciolo** [comment]
@franciscastro This issue is meant to disallow highlighting of the text for the game title and initial instructions in the toolbox when you first come into the editor.

Sometimes the text can get accidentally highlighted when scrolling.

**Comment by sai-educ** [comment]
@mmicciolo @franciscastro This is ready for review.

**Test:** 

- Login to Game Editor (dev platform)
- On the left pane, try highlighting the text (by selecting the text). It should **not** allow any text to be highlighted/selected. 

![Screenshot 2022-02-18 at 12-45-45 wlcp-ui](https://user-images.githubusercontent.com/25312586/154735516-726ae6c1-f5b0-4804-bd23-c5aa0c953953.png)

**Comment by mmicciolo** [comment]
Approved!

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by apoh3** [comment]
@mmicciolo @franciscastro @sai-educ @geseiche 

**Test passed**

I am not able to highlight text.

**Comments:** When hovering over 'Wearable Learning Cloud Platform' and 'No Game Loaded!', the cursor is text:
![image](https://user-images.githubusercontent.com/61091501/156430036-3abb833a-2e30-44cd-a10f-7ebc96447ce3.png)
Since the text is not editable, I suggest that the cursor should be the classic arrow.

**Another tester is needed.**

**Comment by geseiche** [comment]
Test passed. I could not highlight. 

I support Allison's comment about changing the cursor

**Comment by mmicciolo** [comment]
@apoh3 @geseiche 

Agreed.

I have set it so that all non-selectable text uses the default cursor.

Ready for retesting.

**Comment by geseiche** [comment]
Retested. No issues. Test passed.

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
