### ISSUE TITLE
Login : That user does not exist?

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#179]
When entering login details if the user did not exist no error message was displayed.

**Comment by mmicciolo** [comment]
Load indicator but no error before:
![image](https://user-images.githubusercontent.com/23061418/148151924-cea41789-937b-4af9-97a2-a154535666d0.png)

**Comment by mmicciolo** [comment]
Error message fixed now : 
![image](https://user-images.githubusercontent.com/23061418/148151984-18568074-1d79-4d4f-8a71-67833b796c0c.png)

**Comment by mmicciolo** [comment]
This issue addresses a bug where logging in with a username that does not exist did not throw an error message.

Now when you login with a username that does not exist in the system you should receive the following error message:

![image](https://user-images.githubusercontent.com/23061418/148151984-18568074-1d79-4d4f-8a71-67833b796c0c.png)

**Comment by mmicciolo** [comment]
@IvonArroyo @franciscastro @sai-educ  @geseiche @apoh3 

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by apoh3** [comment]
**Test passed**

1. Received "Invalid username or password. Please try again."  after trying usernames issue179user1, issue179user2, and issue179user3 with password asdfasdf.
2. **Created user issue179user1** with password asdfasdf.
3. Logged in with user issue179user1 successfully.

**Comment by sai-educ** [comment]
**Test passed.**

Received "Invalid username or password for _issue179user2_ and _issue179user3_. 
Created user _issue179user2_ with password _cowaBUNG@_
Logged in with user _issue179user2_ successfully.

@mmicciolo @franciscastro @geseiche @apoh3 one more tester needed and this ticket can be closed.

**Comment by geseiche** [comment]
**Test passed**

Received "Invalid username or password for *issue179user3* and *issue179user4*
Created user *issue179user3* with password *test*
Logged in with user *issue179user3* successfully.

@mmicciolo Testing Complete

**Comment by mmicciolo** [comment]
Thank you @apoh3 @sai-educ and @geseiche for testing.

Closing issue.
