### ISSUE TITLE
Game Editor : Remove or replace save button

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#180]
Rename the Save button to something more appropriate since we have auto save now and the only point of the save button is to add a description to a specific version.

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @sai-educ @IvonArroyo 

This issue is ready for testing on dev - https://dev.wearablelearning.org

**Testing Summary**
The save button has been renamed to "Label and Save" and history in the toolbox has been renamed to "Save History"

**Testing Steps**

1. Create a new game
2. Verify the "Label and Save" button exists and works
3. Verify the "Save History" label exists in the clickable toolbox

**Expected Results**
Buttons and labels are properly renamed.

**Comment by apoh3** [comment]
**Test passed**

Label and Save exists and works:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/ef27cd70-2e90-4f55-8169-2b8be7a71c09)

Save History exists and works:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/c5798a0c-192b-47ef-b27c-ed53970d4f23)

**Comment by sai-educ** [comment]
**Test passed.** Working as expected.

<img width="976" alt="Screenshot 2023-05-31 at 1 19 32 PM" src="https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/25312586/30408788-3632-4843-aae4-d0e40bb5a877">

**Comment by mmicciolo** [comment]
Testing complete. Deployed to Prod. Closing Issue.
