### ISSUE TITLE
Game Editor : Main toolbar buttons bunch up when the screen is small

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#184]
Buttons bunch up in wrong order
![image](https://user-images.githubusercontent.com/23061418/148104667-5108fbc5-b97e-4ed0-92bf-f4bdfb9cd2f4.png)

**Comment by mmicciolo** [comment]
Fixed:

... is now prioritized over home and home is hidden within that

![image](https://user-images.githubusercontent.com/23061418/148315523-40f5c56b-5219-44e1-a65b-01e832331a5a.png)
![image](https://user-images.githubusercontent.com/23061418/148315582-e8c4e92c-f010-405b-b763-bc661b57982b.png)

**Comment by apoh3** [comment]
@franciscastro 
@mmicciolo is ready for review.

At the smallest screen width, the main toolbar buttons should be New, Load, and ... . All other buttons should be under ... in the same order as they lie when the screen is fully maximized. As the screen width increases from smallest to maximized, the buttons under ... should become visible in the toolbar and no longer available in ... . At maximized, ... is no longer an option as it contains no buttons.
###
**Fully maximized:**
![image](https://user-images.githubusercontent.com/61091501/154571128-a359f127-8c27-4a76-9ae8-c26998c78489.png)

###
**Smallest screen width:**
![image](https://user-images.githubusercontent.com/61091501/154570679-b6cd5e25-b2fd-407f-a1a3-bde8f8fc082a.png)

###
**Increased width adds buttons to toolbar and removes buttons from ...**
![image](https://user-images.githubusercontent.com/61091501/154571270-51e08c08-4a7c-42f4-a3ab-5319a08b3bfd.png)

###
### Test
Increase and decrease the screen width of the Game Editor. 
1. On increase, check that the buttons are disappearing from ... and appearing in the toolbar in the same order as when the screen is fully maximized. 
2. On decrease, check that the buttons are disappearing from the toolbar and appearing in ... in the same order as when the screen is fully maximized.

**Comment by mmicciolo** [comment]
Approved!

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by geseiche** [comment]
**Test Failed**

When I decrease the size of the screen, the buttons condense in the correct order. When I increase the size of the screen, the buttons reappear in the correct order. This part was successful.

**Bug Found**
When you decrease the size to make the window align with the edge of a button (such as the run and debug button), the ... button (more button) is not visible and can be clicked but only if the cursor is in the exact correct position. See image below.
![image](https://user-images.githubusercontent.com/32133509/156895189-63e9d4fa-e12f-4648-92d3-6e30dd01d3a6.png)

**Comment by mmicciolo** [comment]
Hello @geseiche

I've spent some time looking into this trying to figure out why this would be happening in the editor.

I ended up downloading the UI5 sample for the toolbarheader found here : https://openui5.hana.ondemand.com/entity/sap.tnt.ToolHeader/sample/sap.tnt.sample.ToolHeader

I edited the sample code and commented out lines 53-68 in V.view.xml

The behavior was exactly the same so this makes me think this is either a UI5 bug or intended behavior.

![image](https://user-images.githubusercontent.com/23061418/156961661-5b3b0584-9782-43fc-9bbd-a61eb7147a5b.png)
![image](https://user-images.githubusercontent.com/23061418/156961677-9f7bd1f2-61ab-4421-b994-aa8e8fabd548.png)

I don't like it so I decide to make the home button always appear (should've been this way from the beginning) no matter what and never disappear into the "..." Now it will collapse the other buttons as you get about half way through the home button.

![image](https://user-images.githubusercontent.com/23061418/156961943-a3df6007-d642-41de-9f76-2120d9789ad5.png)
![image](https://user-images.githubusercontent.com/23061418/156961785-359f701d-e35e-447a-86c5-4cd825c656f4.png)

I think this is the best I can get it. I have deployed the latest changes to dev. Please let me know what you think.

**Comment by geseiche** [comment]
@mmicciolo Love the new solution. Works great. **Test Passed.**

**Comment by sai-educ** [comment]
**Test passed.** 

- On decrease, Load, Save, Run and Debug, Undo, Redo (in same order) collapse into the "..." menu 
- On increase, menu items (in the same order) expand into position

Home button remains visible at all times.

**Comment by mmicciolo** [comment]
Testing complete.

Closing ticket.
