### ISSUE TITLE
Game Editor : Bug with sequence and keyboard getting flipped

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#185]
Even though color sequence is at the top of the list (unselected doesn't matter), single button press screen is shown. Same as neighbor transition for a scope should show in this case sequence button.
![image](https://user-images.githubusercontent.com/23061418/148314889-cfd85f51-8393-42b3-8585-af981757f363.png)

**Comment by mmicciolo** [comment]
Function properly now:
![image](https://user-images.githubusercontent.com/23061418/148315467-10fbdb27-b47b-4487-9736-9247b407e22e.png)

**Comment by franciscastro** [comment]
When you open a transition, first one in the list wasn't automatically getting selected -- test to make sure that the first option in transition list is autoselected

**Comment by sai-educ** [comment]
@mmicciolo @franciscastro This is ready for review. 

**Test:**

- Login to Game Editor (dev platform)
- Create a new game with 2 States and 1 Transition (or any structure)
- When you open the Transition, make sure the first item "Button Press" is auto-selected.

![Screenshot 2022-02-18 at 13-43-12 wlcp-ui](https://user-images.githubusercontent.com/25312586/154743947-2aac89f5-46cc-4909-84a2-94cd8f5133e7.png)

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @sai-educ @geseiche @IvonArroyo 

Ready for testing.

Just one minor correction make sure the first item regardless of whether it is a button press or not is always selected when you open up the transition editor.

For example when you setup a state with 2 transitions coming from it and in the left you set a button press or sequence or text and timer, in the right transition the first should always stay selected. 

https://user-images.githubusercontent.com/23061418/148315467-10fbdb27-b47b-4487-9736-9247b407e22e.png

**Comment by apoh3** [comment]
**Test passed**

The first transition type in the list was always selected and the fields to the right matched the selection. Tested multiple game setups.

**Comment by geseiche** [comment]
Test passed - Selected transition type always appeared first and selected

**Comment by mmicciolo** [comment]
Testing complete.
