### ISSUE TITLE
Game Editor : load game double scrolling bars on small screen

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#187]

**Comment by mmicciolo** [comment]
Double scroll bars before : 
![image](https://user-images.githubusercontent.com/23061418/148151637-9ce2e7a7-be5c-4bea-8503-04c5b56f3952.png)

**Comment by franciscastro** [comment]
@mmicciolo will be writing the test script for this

**Comment by mmicciolo** [comment]
This issue addresses a bug where when you are running the editor in a small window and open up the load game dialog, sometimes double scroll bars would show up. One would have to scroll both bars down in order to get to the actual bottom of the page.

**Testing Instructions**

**Comment by mmicciolo** [comment]
@IvonArroyo @franciscastro @sai-educ  @geseiche @apoh3 

Ready for testing. Will need at least 2-3 testers per issue.

Thanks!

**Comment by apoh3** [comment]
**Test passed**

I played with different screen sizes and different variations of "public games" and/or "your games" selected. There was always a max of one scroll bar visible.

**Comment by geseiche** [comment]
**Test passed**

I played with the different screen sizes and different accounts with small and large numbers of games. I only ever saw a maximum of one scroll bar.

**Comment by IvonArroyo** [comment]
Test passed.
I loaded games, following the protocol, opened public and private games, saw only 1 scroll bar.

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
