### ISSUE TITLE
Game Editor : undo/redo dont work for dragging state / transition onto pad

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#188]

**Comment by mmicciolo** [comment]
Should double check all events :
add state
add connection
add transition

edit state
edit transition

move state

delete state
delete connection
delete transition

**Comment by mmicciolo** [comment]
After first drop onto new game working as intended:
![image](https://user-images.githubusercontent.com/23061418/148315664-114b6765-48a5-478f-8c7d-3b090e37b619.png)

**Comment by franciscastro** [comment]
> Should double check all events :
> 
> add state add connection add transition
> 
> edit state edit transition
> 
> move state
> 
> delete state delete connection delete transition

@mmicciolo  Are the above technically all the test script/scenarios that need to be covered for testing this ticket or are there others to add?

**Comment by mmicciolo** [comment]
@franciscastro 

These are all of the scenarios

add state
add connection
add transition

edit state
edit transition

move state

delete state
delete connection
delete transition

**Comment by sai-educ** [comment]
All scenarios have been tested. Undo/redo operations working as intended. 

![188](https://user-images.githubusercontent.com/25312586/152246333-96f2248b-8845-48bf-b1bf-dc7692fcfaa1.gif)

**Comment by sai-educ** [comment]
Hi @mmicciolo, @apoh3 @franciscastro: all scenarios have been tested and the UNDO/REDO button works as intended. Need two more people to test and we this can be closed.

**Comment by apoh3** [comment]
All scenarios were tested and passed. I also tested combinations of the scenarios and those passed too.

**Comment by franciscastro** [comment]
**Scenarios tested**

- [ ] add state
- [ ] add connection
- [ ] add transition

- [ ] edit state
- [ ] edit transition

- [ ] move start state
- [ ] move regular state

- [ ] delete state
- [ ] delete connection
- [ ] delete transition

---
**Findings**

1. All scenarios test and work
2. Some error messages were found in the following scenarios -- in both cases, the errors were the same (see screenshots).

a. Deleted a state that had an incoming connection and transition -- Note: the transition above this state was not empty
b. Deleted a connection with a transition on it -- Note: the transition on this connection was not empty

Screenshot 1: Setup
<img width="963" alt="Screen Shot 2022-02-08 at 2 51 59 PM" src="https://user-images.githubusercontent.com/1910413/153065337-ce79a72a-f0c5-41e5-a98d-b5a00fb745ed.png">

Screenshot 2: Error 1
<img width="962" alt="Screen Shot 2022-02-08 at 2 52 38 PM" src="https://user-images.githubusercontent.com/1910413/153065403-6a3f571e-eca4-45ef-9a2d-1097b5497511.png">

Screenshot 3: Error 2
<img width="962" alt="Screen Shot 2022-02-08 at 2 52 52 PM" src="https://user-images.githubusercontent.com/1910413/153065485-8fd0a18e-33a0-4fdd-afc6-fa14f19c2d13.png">

**Comment by franciscastro** [comment]
@mmicciolo Three testers found have finished with this ticket. I found some errors appearing for certain scenarios.

**Comment by apoh3** [comment]
@mmicciolo

Replicated @franciscastro error a (Deleted a state that had an incoming connection and transition -- Note: the transition above this state was not empty)

![image](https://user-images.githubusercontent.com/61091501/153069253-ce4357b5-bd43-4be9-acd4-a2320efc2b77.png)

**Comment by mmicciolo** [comment]
Testing complete on this one. Bugs found. Will move back to development.

@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Thanks!

**Comment by mmicciolo** [comment]
@IvonArroyo @franciscastro @sai-educ @geseiche @apoh3

Moved bug found to #221 as it is not related to this issue.

Testing complete. Closing issue.
