### ISSUE TITLE
Game Editor: All users assigned to other ...

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#20]
The error message about all users being assigned to other states was not easily understood by the users and could appear in nonapplicable situations.

**Comment by mmicciolo** [comment]
@IvonArroyo Could you look into this if you have some time and come up with a more appropriate message? The current message is : All players and teams have been assigned in neighbor states.

**Comment by mmicciolo** [comment]
@IvonArroyo Would you be able to take a look at this one please?
