### ISSUE TITLE
Game Editor: Highlight selected game in Load Game selection screen

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#209]
**Description**
In the dev version, selecting a game from the list of games displayed in the Load Game selection screen does not highlight the selected game (see screenshot). Thus, it is not clear whether a game has already been selected, unless you look at the "Load" button, which becomes active when a game is selected. Highlighting the selected game would add to the visual cues for the Load Game selection screen.

**Screenshots**

1. Screenshot 1: Load Game screen with no games selected for loading

<img width="690" alt="Screen Shot 2022-02-23 at 9 52 48 AM" src="https://user-images.githubusercontent.com/1910413/155378059-77b216ec-904c-4875-a022-ffbffa021f55.png">

2. Screenshot 2: Load Game screen with a game selected for loading -- the game `test-issue-162` was selected, but there is no indicator that it was selected. The `Load` button, however, is now active

<img width="690" alt="Screen Shot 2022-02-23 at 9 53 03 AM" src="https://user-images.githubusercontent.com/1910413/155378372-33825730-96d1-45fa-98bc-fd5fe72edd7c.png">

**Comment by mmicciolo** [comment]
Copying from #231 


1. Enter the game editor
2. Click Load
3. Click a specific game

Once a game is clicked on, it should be highlighted so the user can see which game they clicked on

**Comment by mmicciolo** [comment]
This fixes a bug where on the load game dialog in the game editor, after selecting a game and removing your mouse the game does not stay highlighted.

**Testing Instructions**

1. Open game editor
2. Click load game
3. Select a game and move the mouse away from the name and off the dialog
4. Game should stay highlighted (selected)

**Comment by geseiche** [comment]
**Test Passed**

Comment: The highlight is very light. Is there any way to darken the color to make it easier to see?

**Comment by franciscastro** [comment]
A selected game on the Load Game selection screen now gets highlighted, but the highlight remains very light.

<img width="691" alt="Screen Shot 2022-05-18 at 3 31 56 PM" src="https://user-images.githubusercontent.com/1910413/169141466-6fe35f88-b96d-4dd0-bf3a-b0246e7d25e3.png">

**Comment by franciscastro** [comment]
Testing complete. Closing this -- refer to #246 for revisiting later once the new UI framework is implemented.
