### ISSUE TITLE
Change default game to private

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#210]
When you create a game in the editor, it should default to private not public.

**Comment by franciscastro** [comment]
To add context to this -- this will also help clean up the publicly-accessible view of games in the game selection screens. At the moment, creating a new game has the "Public" option automatically set -- the goal is to have that be unset as the default behavior when creating new games.

**Comment by mmicciolo** [comment]
Hello @geseiche and @franciscastro 

I am thinking about closing this as it will be taken care of when we implement the game sharing system... #43

Or I could flip the order of the dropdowns in the load game screen for both the editor and manager?

Thoughts?

![image](https://user-images.githubusercontent.com/23061418/165637084-0a28af9f-8ee8-42f9-be50-1f4ffe0409e3.png)

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for testing at http://dev.wearablelearning.org/

This ticket makes an improvement to game creation and no longer defaults to creating public games. Now the default is a private game. This will help keep the public games list more manageable.

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1
The following scenario tests that the default game visibility when creating a new game is private.

**Steps for testing**
1. Login and navigate to the game editor
2. Click "New" button to bring up the create new game dialog
3. The visibility box should be unchecked meaning its a private game
4. Create a game
5. Click "New" button again and make sure the visibility is reset to the default value, still unchecked (private)

## Scenario 2
The following scenario tests that the default game visibility when creating a new game is private.

**Steps for testing**
1. Login and navigate to the game editor
2. Click "New" button to bring up the create new game dialog
3. The visibility box should be unchecked meaning its a private game
4. Check it to make it public
5. Create a game
6. Click "New" button again and make sure the visibility is reset to the default value, still unchecked (private)

## Scenario 3
The following scenario tests that the default game visibility when canceling the dialog.

**Steps for testing**
1. Login and navigate to the game editor
2. Click "New" button to bring up the create new game dialog
3. The visibility box should be unchecked meaning its a private game
4. Check it to make it public
5. Click cancel
7. Click "New" button again and make sure the visibility is reset to the default value, still unchecked (private)

**Comment by apoh3** [comment]
**Test passed** all 3 scenarios

![image](https://user-images.githubusercontent.com/61091501/181590771-8bb386f5-0b84-41cf-badd-55ed75bf9dfb.png)

**Comment by sai-educ** [comment]
All scenarios passed. 
@mmicciolo @franciscastro @apoh3  

![Screen Shot 2022-09-14 at 8 41 59 PM](https://user-images.githubusercontent.com/25312586/190287242-307c5342-a78b-4685-b982-cbc677b09ff5.png)

**Comment by mmicciolo** [comment]
Will be fixing bug found in #219 in this ticket.

**Comment by mmicciolo** [comment]
Thank you @apoh3 and @sai-educ for testing.

I have fixed the bug that @sai-educ mentioned. When you click on "Copy to New Game" and the dialog open, the visibility now defaults to private.

![image](https://user-images.githubusercontent.com/23061418/192113067-7e6d07b9-e079-4146-852f-7797036c2733.png)

Closing issue.
