### ISSUE TITLE
Game Player Display Text + Display Photo Bug

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#216]
There is a bug when connecting to a game twice with a display text an display photo as the first state the text gets stuck at connecting...

![image](https://user-images.githubusercontent.com/23061418/155749944-ec13423e-66c3-462b-8b99-c9fd278c0f0c.png)

This isn't a real connectivity issue but a bug with how some parts of the game player arent being reset when a user disconnects.

Steps to reproduce this bug:

1. Open a new tab / window of WLCP
2. Start a tangrams race instance in the game manager.
3. Click the home button then click on game player tile
4. Enter game pin and select player 1. Once it loads disconnect.
5. Dont refresh the page.
6. Click on game player tile again
7. Enter game pin and select player 1
8. Shows connecting... text but game still fully works

**Comment by mmicciolo** [comment]
This bug has been fixed and temporarily deployed to production (master) : http://new.wearablelearning.org/

**Comment by mmicciolo** [comment]
@franciscastro Ran into this bug during our meeting last week even though I thought I had fixed it. I figured out today how to reproduce it in a different way.

**Steps to reproduce.**

1. Open a new tab / window of WLCP
2. Start a tangrams race instance in the game manager.
3. Click the home button then click on game player tile
4. Enter game pin and select player 1. Once it loads click the back button instead of disconnect.
5. Dont refresh the page.
6. Click on game player tile again
7. Enter game pin and select player 1
8. Shows connecting... text but game still fully works

**Comment by mmicciolo** [comment]
This issue fixes a bug where the "connecting..." text gets stuck on the screen when re-entering a game without refreshing. This is not an actual connection issue, just an issue with some text not getting cleared.

**Testing Steps**

Scenario 1

1. Open a new tab / window of WLCP
2. Start a tangrams race instance in the game manager.
3. Click the home button then click on game player tile
4. Enter game pin and select player 1. Once it loads disconnect.
5. Dont refresh the page.
6. Click on game player tile again
7. Enter game pin and select player 1
8. Game should reload as expected and "connecting..." text should not get stuck like above.

Scenario 2

1. Open a new tab / window of WLCP
2. Start a tangrams race instance in the game manager.
3. Click the home button then click on game player tile
4. Enter game pin and select player 1. Once it loads click the back button instead of disconnect.
5. Dont refresh the page.
6. Click on game player tile again
7. Enter game pin and select player 1
8. Game should reload as expected and "connecting..." text should not get stuck like above.

**Comment by mmicciolo** [comment]
@apoh3 @geseiche @franciscastro @IvonArroyo @sai-educ 

Ready for testing!

**Comment by apoh3** [comment]
**Tests passed**

But...
For scenario 1, before disconnecting I received this message saying that the page would refresh. The scenario script specifically asks for the page to not be refreshed.
![image](https://user-images.githubusercontent.com/61091501/160810672-b73446f7-64f9-4276-8bb7-c1420de3e73f.png)

**Comment by sai-educ** [comment]
**Test passed on Dev system**. However, on new.wearablelearning.org, I've noticed scenario2 (hitting back button) halts on "Connecting...". Tested on Firefox, Safari and Chrome on laptop.

Requesting others to confirm.
@franciscastro @geseiche  

![192](https://user-images.githubusercontent.com/25312586/160897615-551f1a30-7a24-4d7d-aea4-5097936e401d.gif)

**Comment by mmicciolo** [comment]
Testing complete.
