### ISSUE TITLE
DEV allows other users to edit public games

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#219]
I logged in as mmicciolo to edit Tangrams Race, since he is the owner. However, then I logged in as demo and I was still able to edit Tangrams Race. I logged back in as mmicciolo and the changes made by demo were there.

**Comment by mmicciolo** [comment]
@geseiche 

Going to add this to spring 22 development since we will be holding off on the game sharing system #43 till summer 22 milestone.

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for testing at http://dev.wearablelearning.org/

The issues fixes a bug where you can load public games without them being read only. This adds a new feature which is a "read only" game screen for when you load public games.

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1
The following scenario tests that the game editor loads public games in read only mode

**Steps for testing**
1. Login to wlcp
2. Go to game editor
3. Click "Load"
4. Select a public game that does not belong to you.
5. You should load into read only mode where you can only select new, load, run and debug and copy game

## Scenario 2
The following scenario tests that when in read only mode "new" button works

**Steps for testing**
1. Load a public game that does not belong to you
2. Click "new" button and create a game
3. Make sure functionality is normal

## Scenario 3
The following scenario tests that when in read only mode "load" button works

**Steps for testing**
1. Load a public game that does not belong to you
2. Click "load" button and load another game (private and then public)
3. Make sure functionality is normal

## Scenario 4
The following scenario tests that when in read only mode "Run and Debug" button works

**Steps for testing**
1. Load a public game that does not belong to you
2. Click "Run and Debug" button
3. No changes should be saved and the debugger should open
4. Make sure functionality is normal

## Scenario 5
The following scenario tests that when in read only mode "Copy Game" button works

**Steps for testing**
1. Load a public game that does not belong to you
2. Click "Copy Game" button
3. Enter a name and click copy
4. Make sure functionality is normal inside of the copied game

**Comment by apoh3** [comment]
**Test passed** all 5 scenarios

**Comment by sai-educ** [comment]
**All scenarios passed the test**. However, one observation is in scenario #5, when you copy the game, the prompt defaults to Public. This appears to be in contradiction to issue #210. 

Requesting others to confirm @mmicciolo @franciscastro @apoh3

**Comment by mmicciolo** [comment]
Thank you @apoh3 and @sai-educ for testing.

Testing has passed. Going to fix the copy game as part of #210 so I am closing this issue.
