### ISSUE TITLE
Game Editor:  ELSE by leaving sequence blank - replace with "All other" checkbox

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#22]
The ability to leave a color code transition or text box transition blank in order to accept all unassigned inputs was not clear or visible and had to be explained by the researchers.

An idea is to have an option to check that says "all other inputs", or alike.

**Comment by mmicciolo** [comment]
Just about finished with this issue. Following cases:

- Open dialog
- Check box
- Uncheck box
- Check box if its already checked on other transition

**Comment by franciscastro** [comment]
@mmicciolo @IvonArroyo Just updated the title of this issue ticket to more accurately reflect the solution that was developed

**Comment by apoh3** [comment]
@mmicciolo test script ready for review.

This issue introduced the 'All other inputs' checkbox for Color Sequence and Text Entry in the Transition Editor. The original issue was that no checkbox existed and thus people were unaware that leaving a color code or text entry blank was equivalent to accepting all other inputs. 

![image](https://user-images.githubusercontent.com/61091501/154566416-3557b117-68e1-4716-8319-07de3f3e3bfc.png)
![image](https://user-images.githubusercontent.com/61091501/154566489-9cbadef4-f41d-44af-a001-4a5a754d14a3.png)

###
If a Color Sequence or Text Entry is added, then this checkbox should disappear.
![image](https://user-images.githubusercontent.com/61091501/154567385-749028be-8409-4fee-81ed-477c4c301eb4.png)
![image](https://user-images.githubusercontent.com/61091501/154567321-48e1d314-b7cb-4bba-9620-ee90e3e945dd.png)

###
If 'All other inputs' is selected, everything else should disappear.
![image](https://user-images.githubusercontent.com/61091501/154568212-832576f3-d06f-4a4c-9e23-a8270cbceba0.png)
![image](https://user-images.githubusercontent.com/61091501/154568273-4972fa8c-e9be-4d48-b247-ecd1d866ff40.png)


###

### **Test Color Sequence**
1. Create/Load a game and add a new transition.
2. Open the Transition Editor.
3. Select Color Sequence. 'All other inputs' checkbox should be visible.
4. Select Add Sequence, choose a color sequence, and select Accept. 'All other inputs' checkbox should not be visible.
5. Delete the sequence. 'All other inputs' checkbox should be visible again.
6. Select 'All other inputs' checkbox. Everything else should disappear.
7. Unselect 'All other inputs' checkbox. Everything that disappeared should reappear.

### **Test Text Entry**
1. Create/Load a game and add a new transition.
2. Open the Transition Editor.
3. Select Text Entry. 'All other inputs' checkbox should be visible.
4. Select Add Text Entry, type a text entry, and select Accept. 'All other inputs' checkbox should not be visible.
5. Delete the text entry. 'All other inputs' checkbox should be visible again.
6. Select 'All other inputs' checkbox. Everything else should disappear.
7. Unselect 'All other inputs' checkbox. Everything that disappeared should reappear.

### **Test Multiple Transitions - Only One 'All other inputs' Allowed**
1. Create/Load a game and add two new transitions from one single state.
2. In the first transition, select Color Sequence and check 'All other inputs'.
3. In the second transition, select Color Sequence and check 'All other inputs'. An error should appear.
4. Repeat steps 2-3 for Text Entry.

### **Test 'All other inputs' Remains Checked on Save & Load**
1. Create/Load a game with one transition with Color Sequence's 'All other inputs' checked.
2. Save and reload the game. The checkbox should still be checked.
3. Change the transition to Text Entry and check 'All other inputs.'
4. Save and reload the game. The checkbox should still be checked.

**Comment by sai-educ** [comment]
**Test passed.** All scenarios working as expected. @mmicciolo @franciscastro @apoh3 @geseiche Kindly confirm. 

However, an unrelated and random "There was an error saving the game" message popped up when testing this. Tried to reproduce the error but it only occurs randomly - 
![Screenshot 2022-03-01 at 16-12-18 wlcp-ui](https://user-images.githubusercontent.com/25312586/156249912-2464c5e4-d92d-485b-b8dd-662339bcfaef.png)

**Comment by mmicciolo** [comment]
@IvonArroyo @franciscastro @apoh3 @geseiche 

Approved and ready for testing.

**Comment by geseiche** [comment]
All tests passed. No issues

**Comment by mmicciolo** [comment]
Testing complete.

Closing issue.
