### ISSUE TITLE
Issues with transition being deleted indirectly 

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#221]
An error is thrown when a transition is deleted due to a connection or other state being deleted.

- Delete state with connection going to it and transition on that connection
- Delete connection with transition on it
- Delete state with connection coming from it with transition on that connection

Moving from #188 to here

**Comment by mmicciolo** [comment]
More information on this issue can be found in duplicated issue #222

**Comment by mmicciolo** [comment]
**Test Description**
This ticket fixes issues with transitions being deleted indirectly:

1. Removing a connection from state that has a transition on it
2. Removing a state that has a connection going to it with a transition on it
3. Removing a state that has a connection coming from it with a transition on it

Any of those 3 cases would cause a double auto save which would throw an error message.

**Testing Steps**
Create the following game (it will need to be remade for each of the 3 cases below)
![image](https://user-images.githubusercontent.com/23061418/157274840-bf4347b9-b7f4-492f-a95a-b2166f545f77.png)

**Removing a connection from state that has a transition on it**
Remove the connection circled in red from the state. No errors should be thrown and an auto save should be created in the history
![image](https://user-images.githubusercontent.com/23061418/157274586-2a5464a0-837a-421a-b5c1-612878336508.png)

**Removing a state that has a connection going to it with a transition on it**
Remove the state circled in red from the editor. No errors should be thrown and an auto save should be created in the history
![image](https://user-images.githubusercontent.com/23061418/157274793-c5617666-b4a8-4d6a-87f3-64a458a9a32e.png)

**Removing a state that has a connection coming from it with a transition on it**
Remove the state circled in red from the editor. No errors should be thrown and an auto save should be created in the history
![image](https://user-images.githubusercontent.com/23061418/157275412-2998ec17-c4c6-42f4-ab52-a0c586138a15.png)

**Comment by mmicciolo** [comment]
@IvonArroyo @geseiche @franciscastro @apoh3 @sai-educ 

Ready for testing.

**Comment by geseiche** [comment]
**Tests Passed** No issues

**Comment by apoh3** [comment]
**Tests passed**

No error were thrown and auto saves were created.

**Comment by mmicciolo** [comment]
Completed testing myself for 3rd tester.

Closing issue.
