### ISSUE TITLE
(DEV)Error while deleting a State 

### ISSUE THREAD

**Issue by sai-educ** [wearable-learning-cloud-platform/wlcp-issues#222]
Steps to reproduce:

- Login to [Dev system](https://dev.wearablelearning.org)
- Open Game Editor
- Load Game >> search for "Dice 50" (This game is fully built in dev, and not imported from production)
- Try deleting any State to see the error:

![Screenshot 2022-03-07 at 19-45-24 wlcp-ui](https://user-images.githubusercontent.com/25312586/157143744-41bb5a18-5f2a-468b-8d39-613d54ce9bdf.png)

Error text for convenience: 
Batch update returned unexpected row count from update [0]; actual row count:
0; expected: 1; statement executed: update transition set connection=?, game=?
where transition id=?

Other observations:
I was still able to undo the State deletion. The error only seems to appear while deleting States and not for Transitions or Connections.

**Comment by sai-educ** [comment]
@mmicciolo - Not sure if this is related to issue [#217](https://github.com/wearable-learning-cloud-platform/wlcp-issues/issues/217).

Requesting others to run the test script to confirm issue.
@franciscastro @geseiche @apoh3

**Comment by mmicciolo** [comment]
@sai-educ @franciscastro @geseiche @apoh3

I have created a new issue for this one yesterday.

Issue #221 

Closing this issue as its a duplicate.
