### ISSUE TITLE
(Dev) Image from one game appear in a totally different game

### ISSUE THREAD

**Issue by sai-educ** [wearable-learning-cloud-platform/wlcp-issues#223]
Steps to reproduce:

1. Login to [dev system](https://dev.wearablelearning.org)
2. Go to Game Manager
3. Click Start Game at the bottom and start the following two games - 
   **Sai_FractionPyramid** and **Dice 50**, and note the game pins.

Now, we will first play the **Dice 50** game. 
- Open an incognito window and navigate to the [dev system here](https://dev.wearablelearning.org/)
- Click **Play a game!**
- Enter the game pin for **Dice 50** from Step 3
- Enter your name, choose any player and tap **Join**
- You will see the game instructions. Enter _yeehaw_ in the text box to continue.
- **Important step:** In the next screen, you will see an instruction prompting you to enter "14 times 3". Here, enter anything other than 42. For example, 12.
- You will see a "Ooops" visual like so:

<img width="496" alt="Screen Shot 2022-03-07 at 8 50 29 PM" src="https://user-images.githubusercontent.com/25312586/157150122-11dc5282-a264-4f4f-a57c-6d5dc9666c14.png">

Next, we will play the **Sai_FractionPyramid** game.
- Tap **Disconnect** on the top right corner of the window
- Tap **Play a game!** and enter game pin for **Sai_FractionPyramid** from Step 3
- Enter your name, choose any player and tap **Join**
- You will notice the "Ooops" visual from **Dice 50** displayed here. Like so:

<img width="863" alt="Screen Shot 2022-03-07 at 9 00 12 PM" src="https://user-images.githubusercontent.com/25312586/157151167-a4ac35c5-b638-49b8-bbcb-6ca0c123995c.png">

Observation: Image from one game appears in a completely different game. Also noticed this happening when you play both games back to back, suggesting this could be related to cache/cookies. 

Requesting others to run test script to confirm the issue.
@franciscastro @mmicciolo @apoh3 @geseiche

**Comment by mmicciolo** [comment]
Hello @sai-educ 

I think this is related to issue #216 

When you click the disconnect button, parts of the game player aren't being reset.

I have the fix implemented on master. I will add the fix to dev too and we can retest.

**Comment by mmicciolo** [comment]
Hello @sai-educ 

I have fixed this issue in DEV and re-deployed.

Ready for testing.

**Comment by sai-educ** [comment]
Thanks @mmicciolo. I tested this issue and this issue is fixed now. Closing ticket.
