### ISSUE TITLE
Empty transition + States are display text causes player to freeze

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#224]
![image](https://user-images.githubusercontent.com/23061418/157161404-bc8d0cf9-de91-4ed3-8213-15c71c747909.png)

There is also an issue where the game instance loop causes excessive CPU consumption.

TODO: End the game after noTransition() b/c of no connections.

1. No connection
2. Connection with empty transition

**Comment by franciscastro** [comment]
Bug found on September 1, 2022

<img width="1188" alt="Screen Shot 2022-09-01 at 3 21 55 PM" src="https://user-images.githubusercontent.com/1910413/190228583-d8435333-dda0-47db-ac35-f0b0f5ec4209.png">

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @sai-educ @IvonArroyo 

This issue is ready for testing on dev - https://dev.wearablelearning.org

**Testing Summary**
When creating a game with 2 states and 1 transition, if the transition was left empty with the 1st state filled out, the game player would freeze the web browser and crash it.

**Testing Steps**

1. Create a new game
2. Add 2 states
3. Add a connection between start and state 1, state 1 and state 2
4. Fill out a display text in state 1
5. Add a transition to the connection between the 1st state and the start state
6. Run and Debug.

**Expected Results**
Game player and web browser should not freeze. You should see "no transition" being displayed.

**Comment by apoh3** [comment]
**Test passed**

Nothing froze and "No Transition" was displayed

![b](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/fb7c9803-a868-4365-8695-9bf921ad48e8)

**Comment by sai-educ** [comment]
**Test passed. All working as intended.**

![Screenshot 2023-05-31 at 13-13-27 wlcp-ui](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/25312586/f3e9b3c3-fe84-435c-bbe5-372ea87e3193)

**Comment by IvonArroyo** [comment]
Test passed. Worked as intended.

**Comment by mmicciolo** [comment]
Testing complete. Deployed to Prod. Closing Issue.
