### ISSUE TITLE
(Dev) Stacking three/more color sequence hides "Submit/Clear" buttons

### ISSUE THREAD

**Issue by sai-educ** [wearable-learning-cloud-platform/wlcp-issues#225]
Steps to reproduce (requires phone for Game Player testing):

1. Login to [dev system](https://dev.wearablelearning.org) from your PC/laptop
2. Open **Game Manager** and launch **IntegerHopscotch**, and note the game pin
3. Using your phone, navigate to the [dev system](https://dev.wearablelearning.org) and tap **Play a game!** (does not matter logged in or not)
4. Enter game pin from Step 2, enter a name and select any player
5. **Important step:** Navigate until you reach any screen that has a color sequence transition. When on the color sequence screen, keep tapping colors until they stack up three layers like so:

![IMG_3907D4DBF70D-1](https://user-images.githubusercontent.com/25312586/157564321-c9d2f4aa-a6e6-4532-83db-d7eed98c856e.png)

6. You will notice the Submit/Clear buttons become hidden, and pinching/zooming does not seem to show the buttons.

**Other observations/notes:** Issue only seems to occur on mobile phones and not on PC/laptop. Tested on iPhone using Safari and Firefox. 

Requesting others to confirm.
@franciscastro @mmicciolo @apoh3 @geseiche

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @IvonArroyo @sai-educ @geseiche 

Ready for testing!

**Comment by apoh3** [comment]
**Test passed**

Virtual device works as attended. I did not try on an actual phone as @sai-educ's original description intended.

**Comments:**
If a player scrolled all the way to the left, visibly disable the left button so the student knows they'd reach the end. Same for right scrolling.

**Comment by geseiche** [comment]
Test passed on both laptop and phone

**Comment by mmicciolo** [comment]
@apoh3 

I really like the idea of disabling the buttons.

Could you open up a new ticket for this?

Thanks!

**Comment by franciscastro** [comment]
> @apoh3
> 
> I really like the idea of disabling the buttons.
> 
> Could you open up a new ticket for this?
> 
> Thanks!

Hi @apoh3 -- have you opened a new ticket for this? Can you tag this issue in that ticket for tracking?
