### ISSUE TITLE
Game Player Enter Name Wrong Error Thrown

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#232]
From #149

Steps to Recreate

1. Click "Play a game!"
2. Enter a valid game pin
3. On the Enter Name screen, leave the box blank and click continue.

The following message is shown

![image](https://user-images.githubusercontent.com/32133509/156896508-63364fa1-2995-4b4d-a0e8-a06fc540380c.png)

**Comment by mmicciolo** [comment]
This issue fixes a bug where when entering a blank player name, the wrong error message is thrown.


1. Click "Play a game!"
2. Enter a valid game pin
3. On the Enter Name screen, leave the box blank and click continue.
4. You should receive a "That player name is invalid!" error message

**Comment by mmicciolo** [comment]
@geseiche @IvonArroyo @apoh3 @sai-educ @franciscastro 

Ready for testing!

**Comment by apoh3** [comment]
**Test Passed**

![image](https://user-images.githubusercontent.com/61091501/160809633-64a03a87-18d9-4110-a057-e83208290dd8.png)

**Comment by sai-educ** [comment]
**Test passed.**

![Screenshot 2022-03-30 at 13-19-37 wlcp-ui](https://user-images.githubusercontent.com/25312586/160894122-4a5577d9-2526-428e-9d22-533564fa9a47.png)

**Comment by geseiche** [comment]
Test Passed
![image](https://user-images.githubusercontent.com/32133509/163261340-1a45e759-26d9-48ba-8b19-1bff554b9476.png)

**Comment by mmicciolo** [comment]
Testing complete closing issue.
