### ISSUE TITLE
Game Editor: Ran out of space

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#24]
Some participants did not realize that they could drag a state to the bottom of the screen to add more space for their FSM in the Game Editor.

What can we do about this to make it more clear?
We need to add functionality to add more space for their FSM in the Game Editor more visible to the user or change the implementation to be more obvious/intuitive.

In addition, When dragging a state to the bottom of the screen to add more space, once the addition space appeared, sometimes the state being dragged was no longer positioned under the cursor.

**Comment by mmicciolo** [comment]
Made huge improvements on the scrolling to fix this.
