### ISSUE TITLE
Player name already in use

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#240]
Right now when a user enters a player name that is already in use, an error message is displayed. The user is not given an option to try to enter a new name or any suggestions for a new name.

In order to solve this, when a name has already been taken we are going to display a new dialog. This dialog will have the following options:

- Enter a new name
- Dropdown box with suggestions 
- Small link that says "if you are trying to reconnect as X click here"

**Comment by franciscastro** [comment]
Notes from Jan. 11, 2022:
1. Need additional verbiage on the "reconnect as X" — open for suggestions from the team!

**Comment by IvonArroyo** [comment]
I suggest putting the reconnect link at the top, saying "Do you really want to reconnect as Matt?",

**Comment by mmicciolo** [comment]
**DRAFT TEST**

This issue is ready for testing on dev - https://dev.wearablelearning.org

**Testing Summary**
Give the player the option to reconnect, choose a new name or choose an auto-generated name when a name conflict occurs when joining a game instance.

**Testing Steps**

1. Start a game instance in the game manager
2. Open two new private windows. 
3. In private window 1 connect to the newly created game instance as player name "firstplayer" 
4. In private window 2 connect to the newly created game instance as player name "firstplayer" 
5. You should be given the options : reconnect, choose

**Expected Results**
On name conflicts players are given sufficient options to resolve the conflict.

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @sai-educ @IvonArroyo

This issue is ready for testing on dev - https://dev.wearablelearning.org

**Testing Summary**
Give the player the option to reconnect, choose a new name or choose an auto-generated name when a name conflict occurs when joining a game instance.

**Testing Steps**

1. Start a game instance in the game manager. Note down the game pin and logout.
2. Open two new private windows. 
3. In private window 1 connect to the newly created game instance as player name "firstplayer" 
4. In private window 2 connect to the newly created game instance as player name "firstplayer" 
5. You should be given the options : reconnect, choose a new name or choose a autogenerated name
6. Verify all options work as intended

**Expected Results**
On name conflicts players are given sufficient options to resolve the conflict.

**Comment by apoh3** [comment]
**Test passed**

![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/1f967f1d-8031-4bb5-8373-55bd23187f9a)

Reconnect worked:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/60ffa2f2-4dda-4e59-a3f4-a8affce580f9)

Choose a new name worked:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/8c83a608-98f3-459a-828f-e4123c876aed)

Choose an autogenerated name worked:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/aeb2d701-2054-4d33-8bb5-1341e96aaa0a)

**Comment by sai-educ** [comment]
**Test passed.** 

This is a great feature. Thanks @mmicciolo.

**Comment by mmicciolo** [comment]
Testing complete. Deployed to Prod. Closing Issue.
