### ISSUE TITLE
Guest player indicator

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#241]
An indicator should be displayed in both the game player and the gamer manager to show if a player is a guest or not.

This will be done by appending a "*" after their name

**Comment by mmicciolo** [comment]
DRAFT

Ready for testing.

The issues adds a * after the players name in both the game player and the game instance info screen in the game manager.

Testing Steps:
1. Start a game instance
2. Logout of your account
3. Join game instance as a guest and verify there is a * next to your name in the upper left hand corner
4. Click back and do not disconnect
5. Log in with the user you started the game instance with
6. Click on the tile and verify the user in the game instance info screen has a * next to it

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for testing at http://dev.wearablelearning.org/

The issues adds a (guest) after the players name in both the game player (virtual device) and the game instance info screen in the game manager.

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1
The following scenario tests that the game manager and game player displays guest players.

**Steps for testing**
1. Start a game instance
2. Logout of your account
3. Join game instance as a guest and verify there is a (guest) next to your name in the upper left hand corner
4. Click back but do not disconnect
5. Log in with the user you started the game instance with
6. Go to the game manager
7. Click on the tile and verify the user in the game instance info screen has a (guest) next to it

**Comment by apoh3** [comment]
**Test passed**

![image](https://user-images.githubusercontent.com/61091501/181590180-7d4382fb-f314-4d3b-b594-e956c8d91256.png)
![image](https://user-images.githubusercontent.com/61091501/181590305-2d11b396-94d0-407f-9d95-5e6a21b0ec06.png)

**Comment by sai-educ** [comment]
**Test passed.** Working as expected.

**Comment by mmicciolo** [comment]
Thank you @apoh3 and @sai-educ for testing.

Testing has passed.

Closing issue.
