### ISSUE TITLE
Logged in username indicator

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#244]
This feature adds an indicator on the WearableLearning interface that shows the _username_ of the user that is currently logged into the platform.

**Problem this addresses:**
Currently, a user that is logged into the platform is not shown their username. This has been found to be confusing for some users who share their machines with peers (in school settings), where they do not know which user is currently logged in.

**Comment by mmicciolo** [comment]
Ready for testing.

Username indicator has now been added to the following locations:

1. Mode Selection Screen (3 tiles manager, editor, player) at the top header after "Welcome to the Wearable Learning Cloud Platform!"
2. Mode Selection Screen(3 tiles manager, editor, player) in between the logout and help button
3. Game Editor in the side bar

Please test by verifying that the correct username is displayed the locations above.

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for testing at http://dev.wearablelearning.org/

This ticket adds a feature to display the current user that is logged in, in various places.

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1
Username indicator has now been added to various places.

**Steps for testing**

1. Mode Selection Screen (3 tiles manager, editor, player) at the top header after "Welcome to the Wearable Learning Cloud Platform!"
2. Mode Selection Screen(3 tiles manager, editor, player) in between the logout and help button
3. Game Editor in the side bar

**Comment by apoh3** [comment]
**Test passed**

![image](https://user-images.githubusercontent.com/61091501/181589726-95f388fa-a32b-4bbd-badd-26cb792a71a4.png)
![image](https://user-images.githubusercontent.com/61091501/181589757-970ff707-a941-47b9-9081-e6a5dd94e747.png)
![image](https://user-images.githubusercontent.com/61091501/181589808-3576e360-5a5e-4bcc-beb6-6d11803c3d3f.png)

**Comment by sai-educ** [comment]
**Test passed.** 

![Screen Shot 2022-09-14 at 9 07 52 PM](https://user-images.githubusercontent.com/25312586/190289643-b4c4e341-6e55-45a5-aad4-e8533fbb9711.png)
![Screen Shot 2022-09-14 at 9 07 35 PM](https://user-images.githubusercontent.com/25312586/190289644-9b31271b-999d-42dd-ba53-0da301c1cb6d.png)
![Screen Shot 2022-09-14 at 9 07 29 PM](https://user-images.githubusercontent.com/25312586/190289645-f1cc3e3e-a770-42af-b502-0d03a45459af.png)

**Comment by mmicciolo** [comment]
Thank you @apoh3 and @sai-educ for testing.

Testing has passed.

Closing issue.
