### ISSUE TITLE
24 Hour Sessions

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#245]
Sessions in the WLCP should only last 24 hours then you should be automatically logged out.

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for testing at http://dev.wearablelearning.org/

The issues add session expiration. After 24 hours your session will expire. If you have a window open you will receive a popup stating so and then the page will be refreshed. If the session expires when the window is closed, next time you navigate to the wlcp you will be presented to the login screen instead of automatically being logged in.

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1
The following scenario tests that the session expiration works properly.

**Steps for testing**
1. Log out of wlcp
2. Log in to wlcp
3. Leave a window open for 24hr +
4. Verify the session expiration screen popups and when clicking OK the page refreshes

**Comment by apoh3** [comment]
**Test passed**

I checked at ~28 hours and the below message popped up. The page refreshed afterwards.
![image](https://user-images.githubusercontent.com/61091501/184025208-313ca05e-e85f-4d47-a5f0-26443a0b2c42.png)

**Comment by mmicciolo** [comment]
Thank you @apoh3 for testing.

I have tested this myself a few times since we didn't have a 2nd tester. Things look good on my end too so I am going to close this issue.
