### ISSUE TITLE
[BUG - Game Editor Debugger/Simulator]

### ISSUE THREAD

**Issue by franciscastro** [wearable-learning-cloud-platform/wlcp-issues#249]
**Describe the bug**
An error message is shown when playing as Team 1 Player 1, preventing the user from debugging as Team 1 Player 1, even when it is a fresh instance of the debugger and Team 1 Player 1 is not taken.

**To Reproduce**
1. Open a game on the Game Editor
2. Click Run and Debug to start a fresh instance of the debugger
3. Enter appropriate game details and join game as Team 1 Player 1
4. The error message "That team and player are taken! Someone else may have taken it before you." is displayed in a dialog box and the player is not allowed to debug as Team 1 Player 1

**Expected behavior**
The user should be able to debug as Team 1 Player 1 after selecting it from the team/player selection screen.

---

**Screenshots**

![image](https://user-images.githubusercontent.com/1910413/175190656-020ef9d2-a9a2-4c5f-b2bf-7f3aa552bd79.png)

---

**Desktop (please complete the following information, write N/A if not applicable):**
 - OS: Windows
 - Browser: Google Chrome

**Smartphone (please complete the following information, write N/A if not applicable):**
 - N/A

---

**Additional context**
Error was found on June 21, 2022 at about 3:30pm while @franciscastro and @apoh3 were testing out game features for Android development.

**Comment by franciscastro** [comment]
@mmicciolo -- Do you think this could be addressed before July 6, 2022? A study will be implemented that day and this could be problematic.

**Comment by mmicciolo** [comment]
> @mmicciolo -- Do you think this could be addressed before July 6, 2022? A study will be implemented that day and this could be problematic.

@franciscastro Yes I will be able to fix it by then. Will try to get it done either tonight or tomorrow night.

**Comment by mmicciolo** [comment]
Hello @franciscastro @geseiche @apoh3 @IvonArroyo 

I have fixed this bug and it is ready for testing. https://dev.wearablelearning.org

This bug only seems to happen when the game server is heavily loaded and the responses take a long time.

I have started 20 or so game instances to load the server so we can test this.

**Testing Steps**

1. Open a game on the Game Editor
2. Click Run and Debug to start a fresh instance of the debugger
3. Enter appropriate game details and join game as Team 1 Player 1
4. You should see the busy indicator (3 dots) and it should only disappear when the player changes to the "connecting..." screen

Before the busy indicator would disappear before changing to the connecting screen and the user could hit the connect button again this would try to connect again as the same player and thus receive the "That team and player are taken! Someone else may have taken it before you." is displayed in a dialog box and the player is not allowed to debug as Team 1 Player 1" error.

Please also test this using the regular game player.

**Comment by apoh3** [comment]
**Test Passed**

Tested Game Editor and Game Player using a small private game as well as 2 larger public games (TangramsRace and EstimateIt). No issues.

**Comment by franciscastro** [comment]
*Test Passed*

@mmicciolo 

Tested this scenario both in the Game Editor Debugger and in the Game Player with an actual game instance. No issues found.

**Comment by mmicciolo** [comment]
Testing complete. Closing issue.
