### ISSUE TITLE
[BUG - Game Editor] New Game Model UserID Loading Broken

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#253]
**Describe the bug**
When refreshing the game editor screen there is an error and the page does not load. This is because in the newGameModel object in the GameEditor.controller.js the usernameId field is trying to be populated before the model is populated in MainView.controller.js via the SessionHelper.

**To Reproduce**
1. Go to https://dev.wearablelearning.org
2. Go to game editor
3. Click refresh
4. Page will load blank and there will be errors in the console

**Expected behavior**

Same page should always load after refreshing.

**Screenshots**
![image](https://user-images.githubusercontent.com/23061418/177683785-380c5ae9-a0c9-4f98-bdf6-0039c3e5d455.png)

**Additional context**
Only happens on dev or prod can't reproduce locally as frequently.

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @geseiche @IvonArroyo 

Ready for testing.

This fixes an issue where when you refresh the page when the game editor is open, the page doesn't load and you are presented with a blank white screen.

Steps to test:

1. Login
2. Go the game editor
3. Refresh page
4. Should reload editor and present quickstart.
5. You should never get stuck on a blank white screen

**Comment by franciscastro** [comment]
**Test *partially* passed**

No issues found when testing scenarios in the Game Editor of https://dev.wearablelearning.org/.

---
**Bug found**

When refreshing the Game Editor of https://prod.wearablelearning.org/, *sometimes* it loads back the Game Editor with an error message (see screenshot below). The behavior is not consistent as *sometimes* it is successful. This happens whether or not the Quickstart was closed or not prior to refreshing.

<img width="1149" alt="Screen Shot 2022-07-08 at 12 52 49 PM" src="https://user-images.githubusercontent.com/1910413/178037037-129dd50e-d4a3-44f1-8f8e-4f35436d8af6.png">

**Comment by mmicciolo** [comment]
Hello @franciscastro 

I am unable to reproduce this.

Could you make sure you do a ctrl+shift+R to make sure you are loading the latest version and that the cache is clear. Were there any errors in the console?

@geseiche @apoh3 @IvonArroyo 

Would you be able to confirm if you are facing the same issue as Francis above?

**Comment by mmicciolo** [comment]
@franciscastro 

I was able to reproduce this randomly and was able to screenshot the console.

![image](https://user-images.githubusercontent.com/23061418/178128366-12daa89b-3781-4684-b869-1ea49d0f73de.png)

The UI is trying to append a child to the pad before it is rendered.

![image](https://user-images.githubusercontent.com/23061418/178128470-9eb09148-529b-43c7-9eea-534fcde8d391.png)

So on very rare occasions this will cause an exception on the page load if onRouteMatched is called before the page is done rendering and will cause it to show garbage.

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for retesting. Since it doesn't seem to happen too often we can keep an eye out for it for a few days then close this. Fairly certain it's fixed now. I have moved everything to onAfterRendering. These one time setup items really rely on running after the rendering is done and not before (which onRouteMatched could trigger before) so it makes more sense to just completely move them to onAfterRendering. I have also done some various code cleanup tasks.

https://dev.wearablelearning.org
https://prod.wearablelearning.org

**Comment by apoh3** [comment]
**Test Passed**

I refreshed the Game Editor in dev and prod a bunch of times and never once saw an error message or blank white screen.

**Comment by mmicciolo** [comment]
Fixed. Closing issue.
