### ISSUE TITLE
[ENHANCEMENT - Game Editor] Option to clear photo/sound/video after uploaded

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#254]
**Is your feature enhancement request related to a problem? Please describe.**
In the state editor under the video section a feature needs to be added in order to clear out any existing videos if a new one wants to be uploaded.

**Describe the solution you'd like**

- Change button to "Upload new video." If video already exists throw popup saying it will overwrite
- Add another button "Clear Video"
- You cant upload a new video until the current video has been cleared pop up

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @sai-educ @IvonArroyo

This issue is ready for testing on dev - https://dev.wearablelearning.org

**Testing Summary**
There is now a button to clear a photo/sound/video when editing a state.

**Testing Steps**
1. Create a new game
2. Add a single state and connection
3. Edit the state
4. Add a photo and clear
5. Add a sound and clear
6. Add a video and clear
7. Repeat the above steps, but accept the changes between each step.
8. Repeat above steps but make sure clear also stops the media from playing

**Expected Results**
Clear button works as intended.

**Comment by apoh3** [comment]
**Test passed**

Adding then immediately clearing worked as intended.
Adding, accepting, then clearing worked as intended.
Clearing stops sound and video from playing.

**Comment by sai-educ** [comment]
Test passed. "Clear" button visible and working as intended.  

![Screenshot 2023-05-31 at 13-23-13 wlcp-ui](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/25312586/a055b851-cee2-416c-ad23-261315c11130)
![Screenshot 2023-05-31 at 13-22-00 wlcp-ui](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/25312586/1d10d565-59a4-4420-907d-75762ad4a017)
![Screenshot 2023-05-31 at 13-21-48 wlcp-ui](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/25312586/68b6982c-0d48-4c5c-8e33-f97f1595075d)

**Comment by mmicciolo** [comment]
Testing complete. Deployed to Prod. Closing Issue.
