### ISSUE TITLE
[ENHANCEMENT - Game Editor] photo/sound/video Max Upload Size

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#255]
**Is your feature enhancement request related to a problem? Please describe.**
Display the max size of a file someone can upload for a video or sound.

**Describe the solution you'd like**
Add a label describing the max upload size. Add a popup dialog if that max size is exceeded.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @sai-educ @IvonArroyo

This issue is ready for testing on dev - https://dev.wearablelearning.org

**Testing Summary**
A label was added to the photo/sound/video pages in the state editor to indicate the maximum upload size of 50mb

**Testing Steps**
1. Create or open an exisiting game
2. Open a state and check that the proper max upload size label exists
3. Repeat for photo, sound and video

**Expected Results**
Proper label exists to indicate max upload size of 50mb

**Comment by apoh3** [comment]
**Test passed**

Photo:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/ccd96fd9-cb93-4556-8ec9-4da7481f85f6)

Sound:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/781d5478-95db-4a80-9559-bd2fdd6b7c02)

Video:
![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/ab6edf85-e511-499a-be17-cedc63359eb5)

**Comment by sai-educ** [comment]
Test passed.

**Comment by mmicciolo** [comment]
Testing complete. Deployed to Prod. Closing Issue.
