### ISSUE TITLE
[BUG - Game Editor] Issues with unicode

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#257]
**Describe the bug**
Default collation on aws mysql is latin1_swedish_ci. It should be utf8mb4_unicode_ci.

**To Reproduce**
2022-07-27 17:54:17.596 ERROR 11 --- [nio-8082-exec-8] o.h.engine.jdbc.spi.SqlExceptionHelper   : Incorrect string value: '\xF0\x9F\x98\x9C T...' for column 'display_text' at row 1

\xF0\x9F\x98\x9C = 😁

Try entering it as display text on prod or dev. Will error out on save due to incorrect encoding

**Expected behavior**
It should all emojis and ut8 unicode. It should be utf8mb4_unicode_ci.

---

**Screenshots**
n/a

---

**Desktop (please complete the following information, write N/A if not applicable):**
 - OS: Mac
 - Browser: Mozilla Firefox, Google Chrome

**Smartphone (please complete the following information, write N/A if not applicable):**
n/a

---

**Additional context**
n/a.

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for testing at https://prod.wearablelearning.org

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1
Adding utf8 characters (like emoji) to all text input fields.

**Steps for testing**
1. Create a new test game
2. Make sure to cleanup the game after since we are testing on prod
3. Add utf8 chars and emojis to all text input fields (see links below)

**Expected behavior**
No save errors. Characters save properly.

**Screenshots**
n/a

# Additional context
utf8 characters : https://www.fileformat.info/info/charset/UTF-8/list.htm
emojis : https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by apoh3** [comment]
**Test passed.**

![image](https://user-images.githubusercontent.com/61091501/182899065-66bf617c-b82c-45a4-adbf-e7f6c36d4651.png)
![image](https://user-images.githubusercontent.com/61091501/182899261-82f90988-fbe1-4341-ab41-a804ddbf6749.png)

**Comment by sai-educ** [comment]
**Test passed.** Both utf8 and emojis are working as intended.

**Comment by mmicciolo** [comment]
Thank you @apoh3 and @sai-educ for testing.

Testing has passed.

Closing issue.
