### ISSUE TITLE
[BUG - Game Editor] Debugger gets stuck at white screen

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#259]
**Describe the bug**
On random when clicking Run and Debug when editing a game, the debugger looks like it is loading but then loads to a white screen.

![image](https://user-images.githubusercontent.com/23061418/181861863-45325fdb-7a4e-4b1f-92f9-e6887b84fead.png)

**To Reproduce**
1. Load a game
2. Continually Run and Debug until the debugger comes up white
3. It may take a long time, its totally random

**Expected behavior**
Debugger fully  opens all of the time.

Game server startDebugGameInstance should always return a value. Sometimes it returns null due to some bad code.

---

**Screenshots**
![image](https://user-images.githubusercontent.com/23061418/181861918-750aa588-8a27-4b82-8efb-61d50c0a8e16.png)

---

**Desktop (please complete the following information, write N/A if not applicable):**
 - OS: Windows
 - Browser Firefox
 - Version 103.0

---

**Additional context**
n/a

**Comment by mmicciolo** [comment]
@franciscastro @apoh3 @geseiche @IvonArroyo 

Ready for testing at https://prod.wearablelearning.org

# Testing Scenarios
The following scenarios should be tested and successfully pass for this issue to be marked complete and closed.

## Scenario 1
Opening the debugger from the editor results in the player selection screen and never a blank white screen.

**Steps for testing**
1. Create a new test game
2. Make sure to cleanup the game after since we are testing on prod
3. Add some states and transitions
4. Debug game a few times to make sure you never receive a white screen

**Expected behavior**
Debugger always goes to player selection and never a white screen

**Screenshots**
n/a

# Additional context
n/a

**Comment by apoh3** [comment]
**Test Passed**

I debugged a bunch of private and public games of various sizes and the debugger always showed the spinning load animation over a white screen followed by the player selection screen. The debugger never froze on a blank white screen.

**Comment by sai-educ** [comment]
**Test passed.** Performed debugging on private and public games. The debugger did not freeze, and always launched as intended.

**Comment by mmicciolo** [comment]
Thank you @apoh3 and @sai-educ for testing.

Testing has passed.

Closing issue.
