### ISSUE TITLE
[ENHANCEMENT - Game Server/Player] Combined Packet Format 

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#262]
Right now all of the different types of output states and input requests are sent between the game server and game player via individual packets. If there are multiple outputs this could cause them to arrived delayed to each other. It also makes it hard to distinguish what data to expect.

**Describe the solution you'd like**
Combine all of the packets into a new single packet with an organized structure. On the game server playervm side of things data to the device will be sent in a transaction style. At the end of the transaction all of the data is aggregated and sent to the device.

Base payload before. Whole bunch of individual packets (containing json objects)
```json
{
    "displayText" : "myDisplayText"
}
{
    "url" : "https://url"
    "scale" : 100
}
{
    "sequenceButtonPress" : ""
}
```

Base payload after
```json
{
    "outputs" : [],
    "inputs" : []
}
```

Payload with a display text and display photo and request for single button press input.
```json
{
    "outputs" : [{
        "type" : "DISPLAY_TEXT",
        "displayText" : "myDisplayText"
    }, {
        "type" : "DISPLAY_PHOTO",
        "url" : "https://url",
        "scale" : "100"
    }],
    "inputs" : [{
        "type" : "SINGLE_BUTTON"
    }]
}
```

Transpiled game before
```javascript
   OUTPUT_STATE_1 : function() {
      this.playerVM.DisplayText("myDisplayText");
      this.playerVM.DisplayPhoto("https://url",100);
      this.state = this.playerVM.SingleButtonPress(["1", "2", "3", "4"], [states.OUTPUT_STATE_2, states.OUTPUT_STATE_2, states.OUTPUT_STATE_2, states.OUTPUT_STATE_2], ["Red Button", "Green Button", "Blue Button", "Black Button"]);
   },
```

Transpiled game after
```javascript
   OUTPUT_STATE_1 : function() {
      this.playerVM.getTransaction().begin();
      this.playerVM.DisplayText("myDisplayText");
      this.playerVM.DisplayPhoto("https://url",100);
      this.state = this.playerVM.SingleButtonPress(["1", "2", "3", "4"], [states.OUTPUT_STATE_2, states.OUTPUT_STATE_2, states.OUTPUT_STATE_2, states.OUTPUT_STATE_2], ["Red Button", "Green Button", "Blue Button", "Black Button"]);
      this.playerVM.getTransaction().commit();
   },
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by franciscastro** [comment]
Notes from December 14, 2022:

1. Combined packet format
2. Web virtual device uses split format
3. Android app to use new combined format
4. Temporarily deployed to dev for Android work

**Comment by mmicciolo** [comment]
Changes implemented and working properly. Testing complete, this issue can be closed.

Temporarily deployed to dev. Will eventually be merged into prod on next release.
