### ISSUE TITLE
[BUG - Virtual Device] Full game instance shows a blank dropdown

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#264]
**Describe the bug**
When the game is full of players and another tries to connect instead of saying the game is full it shows an empty drop down on the "choose a team and player" dialog as indicated in issue #230 

**To Reproduce**

1. Start a game instance
2. Connect player until the instance is full
3. The next player you to try to connect will get an empty drop down for "choose a team and player" dialog

**Expected behavior**
A message should be thrown that the server is at capacity.

---

**Screenshots**
![image](https://user-images.githubusercontent.com/23061418/192109680-ec94af93-0e3b-48b9-838c-8aca1a614f75.png)

---

**Desktop (please complete the following information, write N/A if not applicable):**
ALL

**Smartphone (please complete the following information, write N/A if not applicable):**
ALL

---

**Additional context**
N/A

**Comment by mmicciolo** [comment]
Add the check after the game pin is entered.

**Comment by franciscastro** [comment]
Notes from Jan. 11, 2023
1. Display a red error message that says something like `This game is already full`

**Comment by mmicciolo** [comment]
**TEST SCRIPT**

This issue is ready for testing on dev - https://dev.wearablelearning.org

**Testing Summary**
When you enter a game pin on the game player and click "join" if the game instance is full a error message should pop up stating "The game instance X is full!"

**Testing Steps**

1. Create a game with 1 team and 1 player per team
2. Add 2 states, connections between them all and a transition between the 1st and 2nd state.
3. Fill out out with some test data
4. Start a game instance of this newly created game via the game manager
5. Logout and open 2 tabs of the game player.
6. Join the game instance with one tab and navigate through to the virtual device screen
7. Attempt to join with the 2nd tab and you should get an error message stating "The game instance X is full!"

**Expected Results**
When you try to join a full game instance you will now receive an error message indicating so.

**Comment by mmicciolo** [comment]
@apoh3 @franciscastro @sai-educ @IvonArroyo

This issue is ready for testing on dev - https://dev.wearablelearning.org

**Testing Summary**
When you enter a game pin on the game player and click "join" if the game instance is full a error message should pop up stating "The game instance X is full!"

**Testing Steps**

1. Create a game with 1 team and 1 player per team
2. Add 2 states, connections between them all and a transition between the 1st and 2nd state.
3. Fill out out with some test data
4. Start a game instance of this newly created game via the game manager
5. Logout and open 2 tabs of the game player.
6. Join the game instance with one tab and navigate through to the virtual device screen
7. Attempt to join with the 2nd tab and you should get an error message stating "The game instance X is full!"

**Expected Results**
When you try to join a full game instance you will now receive an error message indicating so.

**Comment by apoh3** [comment]
**Test passed**

![image](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/61091501/d9481ccf-b066-4092-a248-b79cc05062c0)

**Comment by sai-educ** [comment]
Test passed. 

However, I have a comment to add. We can consider adding a label that tells what can be done next, such as "_Talk to the Game Manager or Facilitator for help_". 

what do you think? @franciscastro @mmicciolo @apoh3 

![Screenshot 2023-05-31 at 13-30-24 wlcp-ui](https://github.com/wearable-learning-cloud-platform/wlcp-issues/assets/25312586/7e8d3d3f-6013-4727-a828-791d3a1b3858)

**Comment by mmicciolo** [comment]
Testing complete. Deployed to Prod. Closing Issue.
