### ISSUE TITLE
[ENHANCEMENT - Game Editor] Security Enhancements

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#265]
**Is your feature enhancement request related to a problem? Please describe.**
This ticket fixes some security issues in the platform.

1. getGame endpoint & getUsername endpoint returning unnecessary fields
2. fixing hard coded jwt secret that was left over during jwt development

**Describe the solution you'd like**
Fix points 1 and 2.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by franciscastro** [comment]
Notes from December 14, 2022:

1. Fixed username data leak
2. Improved JWT security between microservices
3. Implemented on `dev` and `prod`

**Comment by mmicciolo** [comment]
Changes implemented and working properly. Testing complete, this issue can be closed.
