### ISSUE TITLE
[ENHANCEMENT - Game Editor] Adminer DB UI Application Load Balancer

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#268]
**Is your feature enhancement request related to a problem? Please describe.**
Add an application load balancer in front of the adminer app so that it can be accessed via a URL instead of an IP.

**Describe the solution you'd like**
Create ALB
Create new CNAME record to dxyz.wearablelearning.org

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by franciscastro** [comment]
11/30 Update: Already deployed in prod and dev

**Comment by mmicciolo** [comment]
This issue has been fixed. I have updated the URL in the google doc.
@franciscastro

**Comment by mmicciolo** [comment]
Application load balancer for adminer working as intended. Testing complete, this ticket can be closed.
