### ISSUE TITLE
Game Player: Player logged in to two games

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#32]
When playing a game, if a user is already registered to playing another game, the states showed up blank.

An error would be desirable in this case, not allowing the player to join.
Do the players time out? How would a player be free again to play another game?

**Comment by mmicciolo** [comment]
Unable to reproduce. If two users login to the same virtual device for the same game instance it will just be replicated across both devices. Different games, same username will work as well.
