### ISSUE TITLE
Game Player App: Android App

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#35]
Revive Esther's App

Where does the code live?

**Comment by mmicciolo** [comment]
Changing task to creating the new android app @apoh3 and @franciscastro are working on.

**Comment by mmicciolo** [comment]
Hello @apoh3 @franciscastro @IvonArroyo 

I plan on starting: 

- #183 

Soon. I found this STOMP CLIENT library here : https://github.com/NaikSoftware/StompProtocolAndroid that I am going to base my API off of.

Ill basically wrap this library to make it WLCP specific and also use Kotlin.

**Comment by franciscastro** [comment]
This issue will be decomposed into child issues and will be tracked in the [Android Development Project issue tracker](https://github.com/wearable-learning-cloud-platform/wlcp-issues/projects/5)

**Comment by mmicciolo** [comment]
Hello @franciscastro and @apoh3 

Can we close this out now that we have separate issues and project for the Android app?

Matt

**Comment by mmicciolo** [comment]
Closing since we have the android tags, android development project and android milestones now.
