### ISSUE TITLE
Game Manager: invite to erase all previous instances when want to start a new one

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#4]
When running a new instance, we need to invite to erase all previous instances when want to start a new one, as otherwise it is not clear which one is the right instance to join and gets very confusing.

**Comment by geseiche** [comment]
This could be dangerous if there are multiple managers running instances of the same game. They might accidentally delete each other's instances. If we do this, I would suggest only being invited to delete the instances that user started.

Maybe the game manager should only show you game instances that you have started, and maybe admins can see all of the game instances or something like that.

**Comment by mmicciolo** [comment]
This task should involve having the game instances being displayed only be the ones that belong to the current user. This will limit the amount showing and cause much less confusion.

**Comment by mmicciolo** [comment]
Combing this issue into #5
