### ISSUE TITLE
Game Manager: Better look, friendlier interface for running games

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#5]
Better look, a more friendly interface for running games.

Some details are that:
- The arrows to browse game instances are extremely confusing <   > 
- Start "Game Instance" should be changed to "Start games" or "Games Started" as "Instance" is too techie.

**Comment by mmicciolo** [comment]
This task should involve having the game instances being displayed only be the ones that belong to the current user. This will limit the amount showing and cause much less confusion.

**Comment by mmicciolo** [comment]
Also will not show any debug game instances.
