### ISSUE TITLE
Game Editor: Can't Access Game Options From Small Screen

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#52]
When my window is smaller, I see the [ooo] icon in the top horizontal menu to see the rest of the hidden options. However, if I click the [ooo] button and go to game options, nothing appears. I am not give the bubble to Rename, Copy, or Delete games. It is only available if I zoom out or expand my window so that the [ooo] button disappears and all options are shown.

**Comment by mmicciolo** [comment]
Changing this to enhancement as support for smaller mobile devices is not currently there.
