### ISSUE TITLE
Game Editor: Debugger Launches Login

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#62]
If I have been editing logged into the editor for a significant period of time, when I launch the debugger, it opens up the login screen in the new tab instead of the debug instance.

Work around: Log in. Close the tab. Relaunch the debugger.

**Comment by geseiche** [comment]
The issue just occurred about 30 minutes since last log in. Getting slightly more annoying. Work around still works.

**Comment by mmicciolo** [comment]
Due to session expiration.
