### ISSUE TITLE
Grace's correction to messages

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#64]
** In the state editor pop up, change "State Description" to "State Title" and rename the pop up box to be "State Editor" instead of "Configure Output State"

**In the transition editor pop up, change "Configure Input Transition" to "Transition Editor"

**For the transition types, change "Single Button Press" to "Button Press", "Sequence Button Press" to "Color Sequence", and "Keyboard Input" to "Text Entry"

**For the debugger "Already debugging" message, change the message box type and the action names so that the buttons read "New Instance" and "New Player on Existing Instance" instead of "OK" and "Cancel".

**Comment by IvonArroyo** [comment]
I will add the change of "Start here" instead of "Start State"

**Comment by geseiche** [comment]
If you change the "Start State" to "Start Here" then don't forget to change the pop up message that shows up when you click on the start state.

**Comment by geseiche** [comment]
I talked with the rest of the group and we decided that "Start" would be the best terminology.
