### ISSUE TITLE
Game Editor: Cannot Reassign Arrows

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#69]
In the game editor, you cannot pick up the head of an existing arrow and drop it on another state.

Steps to recreate:
1. Add three states to the editor.
2. Connect start to state A
3. Connect state A to state B
4. Try to pick up the arrow just drawn and move it to state C instead
It autosnaps back to where it started.

Is this intended behavior?

**Comment by mmicciolo** [comment]
This is intended behavior. Maybe a info message should be added.

**Comment by mmicciolo** [comment]
The library does not support re-assigning connections so I have just implemented an error message that reads as follows : You cannot move or drop a connection there!
