### ISSUE TITLE
Game Editor: On State Save Title Not Updated

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#71]
The first time opening the state editor, upon saving, the diagram still reads state. You have to open it again and resave to have the title persist.

Steps to recreate.
1. Drag a new state onto the canvas and connect it to the diagram.
2. Double click to open the state editor.
3. Enter a state title and some display text.
4. Click save.
The title of the state still says "State". It should say whatever you typed in.

**Comment by geseiche** [comment]
It appears, this bug only occurs when display text is also entered. Steps to recreate have been updated to reflect this

**Comment by mmicciolo** [comment]
Fixed Issue!
