### ISSUE TITLE
Game Editor: Adding Space to the Builder

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#72]
When using Chrome, dropping a state in the bottom of the white space (Builder) in the editor does not create enough extra space to be useful. The space added is like a quarter of an inch, but it should be at least enough space to fit another state.

Note: This does not occur in Firefox

**Comment by geseiche** [comment]
Update: I no longer think this is a browser issue. I think it might be an issue for of screen resolution.

Space adds fine for chrome on my laptop, but on my large high res monitor the amount of space added is too small.

**Comment by mmicciolo** [comment]
Fixed!
