### ISSUE TITLE
Game Editor: Transition Type Not Loaded In Editor

### ISSUE THREAD

**Issue by geseiche** [wearable-learning-cloud-platform/wlcp-issues#73]
When you open a transition editor of an existing transition, there is nothing selected for the transition type in the left panel. You need to click through the options to figure out where there are options selected to figure out what kind of transition it it.

**Comment by geseiche** [comment]
This might be related to changing the names of the transition types in the i18n files

**Comment by mmicciolo** [comment]
This issue has been fixed!

**Comment by mmicciolo** [comment]
@IvonArroyo ready for testing. Please test in English and Spanish.
