### ISSUE TITLE
Logger: We need to log all user events in Game Editor, ASAP 

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#74]
We really need to start logging all events that a user carries out, every action they perform.

We need:
**user id
session id
game id
Log Context (game editor, debugging, playing)
timestamp**
**Component type** (state, transition, button, N/A, etc.)
**Component ID** (int,  null default)
**Component Properties.** (JSON/XML? for the content tof the dialog components. { {title, "Welcome!  Let's Begin!"} {{Team1}{Team2,  {DisplayText, "Welcome to Integer Hopscotch! "}}}

**User action** (possible actions):
   - Entered game editor
   - Side arrows of tutorial click left of right)
   - Done with tutorial
    -New Game (Note: in properties we have to store game name, player number, team numbers, etc.)
   - Load Game Button in Game Editor
   - Save Game Button
   - Debug Game Button
   - Game Opttitons Button
   - Home Button
   - Help (?) Buttton
   - Reload (power) Button
   - Selection of Public/Your Games (is this possible?)
   - Game Chosen (name of game chosen). (possible?)
   - Load Game Button in Dialog (and which game)
   - Cancel Load Game Button in Dialog
    - Scrolling up (browser level, is this possible?)
    - Scrolling down (browser level, is this possible?)
    - Dragging State on canvas from toolbar
    - Edit State
    - OK Error Dialog Box
    - Delete State
    - OK Delete Dialog Box
    - Drag State within Canvas
    - Connecting State to another state (Note: destination state should be saved in component properties {{from, stateid}, {to, stateid})
    - Dragging Transition on canvas from toolbar
    - Delete Transition
    - Disconnect Transition. (Note: state should be saved in component properties {{from, stateid}, {to, stateid})
    - Edit Transiiton (Note: (JSON/XML? for the properties field {  {Team1,  {{Button, "red,blue"}, {Text Entry, "  "}, {Sequence, "red, blue"}}

    

****WLCP reaction** (**Can be the name of the final function that reacted in some way, such as ErrorPopUp, ShowGame, etc.)
     - Arrow Created. 
     - Transition Created
     - State Created
     - Game Created

****WLCP Reaction Component ID** (component ID generated as part of the reaction, such as gameID, stateID, transitionID, etc.)
**WLCP Reaction Component type

**Comment by mmicciolo** [comment]
Closing this issue as the game editor logger has been live for months now. If there is anymore planned development on this we can open a new issue.
