### ISSUE TITLE
States and Transitions are not editable in new game after errors

### ISSUE THREAD

**Issue by IvonArroyo** [wearable-learning-cloud-platform/wlcp-issues#75]
Try creating a simple game, and dragging arrows before entering text for the state.
You get an error (as expected), and after that, it is very hard to edit any state without getting no reaction from the Game Editor.

<img width="356" alt="Screen Shot 2020-09-15 at 12 16 24 PM" src="https://user-images.githubusercontent.com/5631787/93237532-411ab300-f74e-11ea-8c3b-2a40010b403a.png">

**Comment by mmicciolo** [comment]
Not enough details to replicate issue. Sometimes when there is a very big issue such as an unhandled exception the entire editor will halt. Need more info on what made it halt.
