### ISSUE TITLE
Autosave games

### ISSUE THREAD

**Issue by mmicciolo** [wearable-learning-cloud-platform/wlcp-issues#84]
Need discussing on when to auto...

Auto save after session expires (what if student didn't want it saved?)

**Comment by IvonArroyo** [comment]
Hi Matt,

When does the session expire?
We should probably not autosave after the session expires.
Also, how often do you autosave?

------
Ivon Arroyo              https://advancedlearningtech.com/
Associate Professor
College of Education and College of Computer Science
A259 LGRC (CICS) and Furcolo W261 (College of Ed)
University of Massachusetts Amherst

Pronouns: She/Her

**Comment by mmicciolo** [comment]
Closing this issue because it is being merged into #150
